def add_remaining(EXHIBITS, exhibit, trad, clash, src, glance_rows):
    EXHIBITS["free-will"] = exhibit(
        id="free-will", domain="Salvation", title="Free Will", latin="Liberum Arbitrium",
        centralQuestion="What can the fallen will do, and what must grace do first?",
        definition="Free will concerns the human capacity to act knowingly and voluntarily. Christian theology asks how this freedom is wounded by sin, restored by grace, and held together with providence.",
        lead="Pelagius, Augustine, Eastern synergy, Aquinas’s distinctions, Luther’s Bondage of the Will, Calvin, and later Arminian replies map one argument: whether the fallen will can begin to turn to God.",
        questionQuote="After the Fall, is the will bound, wounded, or still able to take the first step?",
        questionNote="All four traditions reject a freedom that makes grace unnecessary. They clash over conversion, resistance, and whether ‘free’ means ‘able to choose God unaided.’",
        deeperQuestions=["Can the fallen will initiate conversion?", "Is cooperation itself a gift?", "Does providence determine choices?", "Is freedom compatible with election?"],
        glance={"rows": glance_rows([
            ("After the Fall", ["Wounded but not destroyed; needs healing grace.", "Impaired image; freedom remains real.", "Bound will: cannot turn to God by nature.", "Total inability in spiritual things."]),
            ("Conversion", ["Will cooperates under operating and cooperating grace.", "Synergy: God initiates, the person freely responds.", "Passive in conversion; faith created by the Word.", "Regeneration precedes the free act of faith."]),
            ("Resistance", ["Actual grace can be refused.", "God does not compel.", "The Spirit can be rejected.", "Effectual calling of the elect is not finally defeated."]),
        ])},
        traditions=[
            trad("catholic", "Catholic", "Freedom remains; it is healed, not replaced, by grace.",
                 ["Catholic teaching, drawing on Augustine against Pelagius and on Aquinas, holds that the will remains after the Fall but cannot attain the supernatural end without grace. Operating grace moves the will; cooperating grace works with it. Coercion is not salvation.",
                  "Trent rejects both Pelagian self-salvation and a bondage that makes all cooperation impossible. Councils also reject a freedom that makes grace a mere aid to an already sufficient nature."],
                 "If God created freedom, He saves it by healing it. Scripture’s commands to repent would be a mockery if no real response were possible, and a lie if the response were unaided.",
                 "Lutherans and Reformed argue that this underestimates the bondage of the will and reintroduces a human share in conversion.",
                 "Catholic theology answers that the ‘yes’ is itself enabled. Secondary causality is not rivalry with God; it is how God ordinarily works in persons.",
                 [{"id": "augustine", "name": "Augustine"}, {"id": "aquinas", "name": "Thomas Aquinas"}, {"id": None, "name": "Council of Trent"}]),
            trad("orthodox", "Eastern Orthodox", "Freedom of the image; synergy, not compulsion.",
                 ["The East never adopted Augustine’s later predestinarian edge as a system. Freedom belongs to the image of God. After the Fall it is darkened and weakened by death, yet not annihilated. Synergy is the native grammar.",
                  "Prayer, ascesis, and the mysteries are the school of a will being healed. God knocks; He does not break the door as a tyrant."],
                 "A salvation that abolishes the person is not the Gospel of the Incarnation. The Word assumed a human will (Maximus) and healed willing from within.",
                 "Western Augustinians hear an incomplete doctrine of original sin. Some Orthodox replies have overreacted against any Western language of inability.",
                 "Orthodoxy reads inability as corruption and mortality more than as a legal incapacity. The medicine is illumination and life, not a replacement will.",
                 [{"id": "maximus", "name": "Maximus the Confessor"}, {"id": "gregory-nyssa", "name": "Gregory of Nyssa"}, {"id": "palamas", "name": "Gregory of Palamas"}]),
            trad("lutheran", "Lutheran", "The bound will and the creating Word.",
                 ["Luther’s Bondage of the Will against Erasmus argues that in matters of salvation the fallen will is not free to choose God. Conversion is God’s work through the Word. The Formula of Concord distinguishes civil righteousness from spiritual powers.",
                  "Once regenerated, the Christian will cooperates in the new life, yet remains simul justus et peccator. Grace is resistible: the same Word that creates faith can be refused."],
                 "If the will can prepare itself, the Gospel becomes law and the conscience is thrown back on itself. ‘It is God who works in you’ must be allowed to stand.",
                 "Catholics and Orthodox hear a denial of the image. Reformed critics want a more consistent account of why resistible grace does not make conversion a human achievement after all.",
                 "Lutherans distinguish the will’s bondage in conversion from the new obedience of the regenerate, and locate resistibility in the tragedy of unbelief, not in a neutral choosing-machine.",
                 [{"id": "luther", "name": "Martin Luther"}, {"id": "melanchthon", "name": "Philip Melanchthon"}, {"id": None, "name": "Formula of Concord"}]),
            trad("reformed", "Reformed / Calvinist", "Inability, then a will made willing.",
                 ["Reformed theology teaches that the natural man does not receive the things of the Spirit. Regeneration is a change of heart that precedes faith. The renewed will then believes freely—freedom of spontaneity, not of indifference.",
                  "Dort rejected Arminian sufficient-but-resistible grace as the last word for the elect. Moral persuasion without regeneration does not raise the dead."],
                 "Commands do not imply ability; they reveal duty and impotence, driving the sinner to grace. A will that can finally defeat God’s saving purpose makes man the decisive cause.",
                 "Lutherans, Catholics, Orthodox, and Arminians argue that this threatens the sincerity of the universal call and the reality of responsibility.",
                 "Reformed writers distinguish the external call, genuinely offered, from the inward call that never fails in the elect. Responsibility attaches to what we want; regeneration changes the want.",
                 [{"id": "calvin", "name": "John Calvin"}, {"id": None, "name": "Synod of Dort"}, {"id": "augustine", "name": "Augustine"}]),
        ],
        agreements=["Pelagianism is false.", "Grace is necessary for salvation.", "Human beings are not puppets in civil life.", "Commands to repent are real.", "God is not the author of sin."],
        clashes=[
            clash("I. Can the fallen will begin conversion?", ["Not unaided; it can consent under grace.", "It can respond within synergy.", "No; conversion is God’s work.", "No; regeneration precedes faith."]),
            clash("II. Is converting grace resistible?", ["Yes, as to actual graces.", "Yes; God does not compel.", "Yes.", "Not finally, for the elect."]),
        ],
        timeline=[
            {"date": "c. 412–430", "title": "Augustine vs Pelagius", "figureId": "augustine", "significance": "Fixed the Western conviction that grace is prior.", "extra": "On Grace and Free Will; On Nature and Grace."},
            {"date": "7th c.", "title": "Maximus and the two wills of Christ", "figureId": "maximus", "significance": "Dyothelitism grounds the healing of human willing.", "extra": "The human will is assumed and deified, not cancelled."},
            {"date": "1525", "title": "Luther vs Erasmus", "figureId": "luther", "significance": "Bondage of the Will vs. a humanist defense of choice.", "extra": "The Reformation’s sharpest text on the will."},
            {"date": "1547 / 1577 / 1619", "title": "Trent, Formula of Concord, Dort", "figureId": None, "significance": "Three classical settlements of the same question.", "extra": "Still the confessional map."},
        ],
        sources=[
            src("Catholic Encyclopedia", "Free Will", "https://www.newadvent.org/cathen/06259a.htm", "New Advent"),
            src("Augustine", "On Grace and Free Will", "https://www.newadvent.org/fathers/1510.htm", "New Advent"),
            src("Augustine", "On Nature and Grace", "https://www.newadvent.org/fathers/1503.htm", "New Advent"),
            src("Thomas Aquinas", "ST I-II QQ.109–114", "texts/summa.html?part=prima-sec&q=109&a=1", "Treatise on Grace"),
            src("Martin Luther", "Bondage of the Will", "https://www.ccel.org/ccel/luther", "CCEL"),
            src("Formula of Concord", "Free Will", "https://bookofconcord.org/", "Book of Concord"),
            src("John Calvin", "Institutes II.2–5", "https://www.ccel.org/ccel/calvin/institutes", "CCEL"),
        ],
        thread=[{"id": "original-sin", "name": "Original Sin"}, {"id": "free-will", "name": "Free Will", "current": True},
                {"id": "grace", "name": "Grace"}, {"id": "predestination", "name": "Predestination"}],
        related=[{"id": "grace", "name": "Grace"}, {"id": "original-sin", "name": "Original Sin"},
                 {"id": "predestination", "name": "Predestination"}, {"id": "justification", "name": "Justification"}],
    )

    EXHIBITS["original-sin"] = exhibit(
        id="original-sin", domain="Anthropology", title="Original Sin", latin="Peccatum Originale",
        centralQuestion="What did Adam’s fall do to the rest of us?",
        definition="Original sin names the wounded condition of humanity after the first disobedience: a disorder of nature, a need for grace, and—on Western accounts—a guilt or liability inherited in Adam.",
        lead="Augustine’s reading of Romans 5, Eastern talk of ancestral mortality, Trent, Luther, and Calvin all confess a real Fall. They clash over inherited guilt, concupiscence, and what baptism does to it.",
        questionQuote="Are we born guilty, or born mortal and inclined to sin—or both?",
        questionNote="All four traditions baptize infants (classically) and deny Pelagian innocence. The argument is about guilt, corruption, and remaining concupiscence.",
        deeperQuestions=["Is guilt transmitted, or only death and inclination?", "What does baptism remove?", "Is concupiscence itself sin?", "How does this touch Mary, the Immaculate Conception, and the East’s silence?"],
        glance={"rows": glance_rows([
            ("What is inherited", ["Guilt and a wounded nature (concupiscence).", "Death, corruption, inclination; guilt language restrained.", "Guilt and total corruption of spiritual powers.", "Guilt and total depravity in spiritual things."]),
            ("Baptism", ["Remits original guilt; concupiscence remains, not counted as sin in itself.", "Illumination and new life; ancestral effects healed along the path.", "Regenerates; remaining sin still truly sin, covered in Christ.", "Washes guilt; remaining corruption is still sin, not imputed to the justified."]),
            ("Concupiscence", ["Tinder of sin, not sin itself in the baptized.", "Passions to be healed, not a legal remainder.", "The flesh is still sinful in the justified.", "Remaining sin in the regenerate; mortified, not eradicated."]),
        ])},
        traditions=[
            trad("catholic", "Catholic", "Inherited guilt remitted in baptism; nature wounded.",
                 ["Trent teaches that Adam’s sin is transmitted by propagation, not mere imitation, and that baptism remits its guilt. Concupiscence remains as a wound and a field of battle, but in the baptized it is not itself sin unless consented to.",
                  "The Immaculate Conception is a later Catholic definition about Mary’s preservation from original sin by a singular grace. It is not shared with the East or with Protestants."],
                 "Romans 5 and the Church’s practice of infant baptism imply that infants need more than a good example. A purely environmental Fall cannot explain the universality of the need for Christ.",
                 "The East resists inherited guilt as a Latin over-reading. Protestants argue that calling remaining concupiscence ‘not sin’ underestimates the law’s verdict.",
                 "Catholic theology distinguishes the guilt remitted from the disorder remaining, and reads Romans 7 in the justified as concupiscence, not as a second original guilt.",
                 [{"id": "augustine", "name": "Augustine"}, {"id": "aquinas", "name": "Thomas Aquinas"}, {"id": None, "name": "Council of Trent"}]),
            trad("orthodox", "Eastern Orthodox", "Ancestral sin: mortality and corruption.",
                 ["Eastern theology typically speaks of ancestral sin: we inherit death, a darkened mind, and a tendency to sin, rather than Augustine’s transmitted personal guilt of Adam’s act. Infants are baptized into life, not primarily as already condemned criminals.",
                  "The Fall is cosmic: the world is subjected to corruption. Salvation is therefore therapeutic and ontological—theosis—not only forensic."],
                 "If the primary disaster is death, the medicine is the destruction of death. Romans 5 is read with 1 Corinthians 15: in Adam all die; in Christ all shall be made alive.",
                 "Augustinians argue this softens Paul’s ‘made sinners’ and infant need. Some Orthodox caricatures of Augustine are historically unfair.",
                 "Orthodoxy still baptizes infants and still preaches the necessity of Christ. The disagreement is about the legal shape of the inheritance, not about the need for a Savior.",
                 [{"id": "athanasius", "name": "Athanasius"}, {"id": "gregory-nyssa", "name": "Gregory of Nyssa"}, {"id": "maximus", "name": "Maximus the Confessor"}]),
            trad("lutheran", "Lutheran", "Original sin as deep corruption, remaining in the regenerate.",
                 ["The Augsburg Confession and Formula of Concord teach a real inherited guilt and a corruption so deep that by nature we cannot fear, love, or trust God. Baptism regenerates; remaining sin in the Christian is still truly sin, forgiven in Christ.",
                  "Luther refused any account that made concupiscence a mere ‘tinder’ rather than sin. Simul justus et peccator is the anthropological counterpart."],
                 "David’s ‘in sin did my mother conceive me’ and Paul’s ‘by nature children of wrath’ will not bear a merely environmental reading. The law must be allowed to convict to the root.",
                 "Catholics hear a confusion of wound with guilt in the baptized. The East hears an Augustinian severity alien to the Greek Fathers. Reformed critics want a tighter link to limited atonement and perseverance.",
                 "Lutherans reply that to deny remaining sin is to weaken repentance. Forgiveness, not interior sinlessness, is the Christian’s peace.",
                 [{"id": "luther", "name": "Martin Luther"}, {"id": "melanchthon", "name": "Philip Melanchthon"}, {"id": None, "name": "Formula of Concord"}]),
            trad("reformed", "Reformed / Calvinist", "Original guilt and total depravity.",
                 ["Reformed confessions teach imputation of Adam’s guilt and corruption of every faculty in spiritual things. ‘Total’ depravity means extent, not that every person is as evil as possible. Common grace restrains; saving grace regenerates.",
                  "Federal or covenantal headship (Adam / Christ) is the typical frame of Romans 5 in later Reformed orthodoxy."],
                 "If Christ is a representative head, Adam was also. Deny the first imputation and the second becomes unintelligible.",
                 "Lutherans share much but clash on remaining sin’s relation to baptismal regeneration and on election. Catholics and Orthodox reject the federal scheme as too legal.",
                 "Reformed theology treats federal headship as Paul’s own parallel, not a modern legalism imposed on the text.",
                 [{"id": "calvin", "name": "John Calvin"}, {"id": "augustine", "name": "Augustine"}, {"id": None, "name": "Westminster Confession"}]),
        ],
        agreements=["The Fall is real and universal.", "Christ is the second Adam.", "Infant baptism (classically) implies infant need.", "Pelagian innocence is false.", "Concupiscence is a field of struggle."],
        clashes=[
            clash("I. Inherited guilt?", ["Yes; remitted in baptism.", "Ancestral death more than inherited guilt.", "Yes.", "Yes, by federal imputation."]),
            clash("II. Remaining concupiscence", ["Not sin in itself in the baptized.", "Passions to be healed.", "Still truly sin, forgiven.", "Still sin, not imputed to the justified."]),
        ],
        timeline=[
            {"date": "c. 412–418", "title": "Augustine and the Council of Carthage", "figureId": "augustine", "significance": "Western condemnation of Pelagius.", "extra": "On the Merits and Forgiveness of Sins; On Nature and Grace."},
            {"date": "1546", "title": "Trent, Session V", "figureId": None, "significance": "Catholic definition of original sin and baptism.", "extra": "New Advent, Original Sin."},
            {"date": "1530 / 1577", "title": "Augsburg II and Formula of Concord I", "figureId": "luther", "significance": "Lutheran definition of inherited corruption.", "extra": "Book of Concord."},
        ],
        sources=[
            src("Catholic Encyclopedia", "Original Sin", "https://www.newadvent.org/cathen/11312a.htm", "New Advent"),
            src("Augustine", "On the Merits and Forgiveness of Sins", "https://www.newadvent.org/fathers/1501.htm", "New Advent"),
            src("Thomas Aquinas", "ST I-II Q.81–85", "texts/summa.html?part=prima-sec&q=82&a=1", "Original sin"),
            src("Augsburg Confession", "Article II", "https://bookofconcord.org/augsburg-confession/", "Book of Concord"),
            src("John Calvin", "Institutes II.1–3", "https://www.ccel.org/ccel/calvin/institutes", "CCEL"),
            src("Athanasius", "On the Incarnation", "https://www.newadvent.org/fathers/2802.htm", "New Advent"),
        ],
        thread=[{"id": "original-sin", "name": "Original Sin", "current": True}, {"id": "baptism", "name": "Baptism"},
                {"id": "grace", "name": "Grace"}, {"id": "free-will", "name": "Free Will"}],
        related=[{"id": "baptism", "name": "Baptism"}, {"id": "grace", "name": "Grace"},
                 {"id": "atonement", "name": "Atonement"}, {"id": "theosis", "name": "Theosis"}],
    )

    EXHIBITS["sacraments"] = exhibit(
        id="sacraments", domain="Sacraments", title="Sacraments", latin="Sacramenta",
        centralQuestion="How many holy signs are there, and do they give the grace they signify?",
        definition="Sacraments are sacred signs entrusted to the Church through which divine life is signified and, on most classical accounts, communicated. They join visible forms to God’s gracious work.",
        lead="The word sacramentum once named many mysteries. The Latin seven, the Eastern mysteries, and the Reformation’s two (or two-plus-rites) are rival enumerations of one instinct: God works through embodied signs.",
        questionQuote="Do the sacraments confer grace, or only represent a grace given otherwise?",
        questionNote="All four traditions keep baptism and the Lord’s Supper. They clash over number, ex opere operato, and whether confirmation, penance, orders, marriage, and unction are sacraments.",
        deeperQuestions=["How many sacraments?", "Does the rite confer grace by being done, or by faith?", "What belongs to validity?", "Are they necessary for salvation?"],
        glance={"rows": glance_rows([
            ("Number", ["Seven.", "Mysteries; seven commonly listed, not scholastically fenced.", "Two: Baptism and the Altar. Other rites may be retained.", "Two: Baptism and the Lord’s Supper as sacraments proper."]),
            ("Efficacy", ["Ex opere operato, given a right minister and no obstacle.", "God’s work in the mysteries; not a Latin legal formula.", "They give what they promise when received in faith; not empty signs.", "Signs and seals; the Spirit uses them with faith, not magically."]),
            ("Necessity", ["Ordinary means; baptism ordinarily necessary.", "Ordinary path of life in the Church.", "Baptism and Supper as means of grace; faith clings to the promise.", "Ordinary means of grace; not absolutely necessary apart from the Word."]),
        ])},
        traditions=[
            trad("catholic", "Catholic", "Seven sacraments as instruments of grace.",
                 ["Catholic doctrine counts seven, instituted by Christ, which confer the grace they signify. Ex opere operato means the rite is God’s instrument, not a reward of the minister’s holiness—yet a recipient’s obstacle (e.g. unbelief, mortal sin) can block fruit.",
                  "Aquinas’s treatise and Trent’s canons remain the Latin map: character in baptism, confirmation, orders; penance as a second plank after shipwreck."],
                 "If the Incarnation is God acting through flesh, sacramental instrumentality is the same logic continued. A purely mental religion is less incarnational, not more spiritual.",
                 "Protestants argue that seven cannot be proved from Scripture and that ex opere operato encourages superstition. The East resists the Latin legal packaging even where it keeps the rites.",
                 "Catholic theology answers that the number is the Church’s discernment of Christ’s institution, and that ‘ex opere operato’ protects the primacy of God’s action, not magic.",
                 [{"id": "aquinas", "name": "Thomas Aquinas"}, {"id": "augustine", "name": "Augustine"}, {"id": None, "name": "Council of Trent"}]),
            trad("orthodox", "Eastern Orthodox", "The holy mysteries of the Church.",
                 ["Orthodoxy speaks of mysteries rather than a closed Latin seven, though baptism, chrismation, Eucharist, repentance, orders, marriage, and unction are standard. Efficacy is God’s personal action in the Church’s liturgy, not a separable created causality.",
                  "Chrismation is given with baptism. There is no Latin-style ‘confirmation gap’ as a later childhood rite in the same way."],
                 "The Church’s life is sacramental because the Incarnation is sacramental. To reduce the mysteries to teaching-aids is to Nestorianize the Church’s body.",
                 "Latin lists and Protestant reductions both seem to Westernize a liturgical organism into a system of countable instruments.",
                 "Orthodoxy can use ‘seven’ pedagogically while insisting the whole of the liturgical life (blessing of water, icons, the year) participates in the same mystery.",
                 [{"id": "chrysostom", "name": "John Chrysostom"}, {"id": None, "name": "Cyril of Jerusalem"}, {"id": "palamas", "name": "Gregory of Palamas"}]),
            trad("lutheran", "Lutheran", "Means of grace: the Word attached to elements.",
                 ["Lutheranism counts baptism and the Lord’s Supper as sacraments by a strict definition (command, earthly element, heavenly promise). Absolution is often treated as a sacrament in a broader sense. Confirmation, marriage, orders, and unction may be retained as rites, not as sacraments of the same rank.",
                  "The sacraments are means of grace: they actually give the forgiveness they promise, not because of the work as work, but because of the Word."],
                 "God has bound Himself to particular promises. Faith does not create the gift; it receives it. To make the sacraments mere badges of our faith reverses the Gospel.",
                 "Catholics hear a truncated list. Reformed critics hear a too-realistic ‘gives grace’ that threatens the distinction of sign and thing.",
                 "Lutherans reply that number follows definition, and that realism about baptismal regeneration and the Supper is simply taking the words as they stand.",
                 [{"id": "luther", "name": "Martin Luther"}, {"id": "melanchthon", "name": "Philip Melanchthon"}, {"id": None, "name": "Augsburg Confession"}]),
            trad("reformed", "Reformed / Calvinist", "Signs and seals of the covenant of grace.",
                 ["The Westminster and Heidelberg traditions count two sacraments as signs and seals. They confirm faith and exhibit Christ; they do not work by a power in the elements. Baptism of infants follows from covenant membership; the Supper requires discerning faith.",
                  "Calvin’s ‘spiritual eating’ and the rejection of ex opere operato are central. Word and sacrament belong together; the Word is the primary means."],
                 "If the elements automatically conferred grace, unbelievers would be saved by a rite and the Incarnate Christ’s heavenly location would be ignored. Signs must remain signs even as they are true seals.",
                 "Lutherans hear a Nestorian gap between sign and gift. Catholics hear a denial of instrumental causality. Baptists later reject infant baptism on Reformed premises taken further.",
                 "Reformed theology insists the Spirit can truly use signs without being bound as a prisoner of the elements. The covenant, not a ritual engine, is the frame.",
                 [{"id": "calvin", "name": "John Calvin"}, {"id": None, "name": "Heidelberg Catechism"}, {"id": None, "name": "Westminster Confession"}]),
        ],
        agreements=["Baptism and the Lord’s Supper are Christ’s.", "Sacraments are not human inventions of the moment.", "They involve Word (or divine naming) and a visible action.", "Unworthy use is possible.", "They belong to the Church, not to private magic."],
        clashes=[
            clash("I. How many?", ["Seven.", "Mysteries (seven commonly).", "Two (plus perhaps absolution).", "Two."]),
            clash("II. Do they confer grace?", ["Yes, as instruments.", "Yes, as God’s action in the liturgy.", "Yes, by the promise, received in faith.", "They seal and exhibit; the Spirit gives with faith."]),
        ],
        timeline=[
            {"date": "c. 400", "title": "Augustine on signs", "figureId": "augustine", "significance": "Visible word; the Latin theology of sign and thing.", "extra": "On Christian Doctrine; anti-Donatist writings."},
            {"date": "13th c.", "title": "Peter Lombard and Aquinas", "figureId": "aquinas", "significance": "Seven sacraments become the Latin standard.", "extra": "ST III on the sacraments."},
            {"date": "1547–1563", "title": "Trent on the sacraments", "figureId": None, "significance": "Seven, efficacy, and canons against Reformation reductions.", "extra": "New Advent, Sacraments."},
            {"date": "1520s–1563", "title": "Reformation definitions", "figureId": "luther", "significance": "Two means of grace vs. seven instruments.", "extra": "Augsburg XIII; Calvin Inst. IV.14."},
        ],
        sources=[
            src("Catholic Encyclopedia", "Sacraments", "https://www.newadvent.org/cathen/13295a.htm", "New Advent"),
            src("Augustine", "On Christian Doctrine", "https://www.newadvent.org/fathers/1202.htm", "New Advent"),
            src("Thomas Aquinas", "ST III QQ.60–65", "texts/summa.html?part=tertia&q=60&a=1", "On the sacraments"),
            src("Augsburg Confession", "Article XIII", "https://bookofconcord.org/augsburg-confession/", "Book of Concord"),
            src("John Calvin", "Institutes IV.14", "https://www.ccel.org/ccel/calvin/institutes", "CCEL"),
            src("Cyril of Jerusalem", "Catechetical Lectures", "https://www.newadvent.org/fathers/3101.htm", "New Advent"),
        ],
        thread=[{"id": "baptism", "name": "Baptism"}, {"id": "sacraments", "name": "Sacraments", "current": True},
                {"id": "eucharist", "name": "Eucharist"}, {"id": "church", "name": "Church"}],
        related=[{"id": "eucharist", "name": "Eucharist"}, {"id": "baptism", "name": "Baptism"},
                 {"id": "grace", "name": "Grace"}, {"id": "church", "name": "Church"}],
    )

    EXHIBITS["scripture-tradition"] = exhibit(
        id="scripture-tradition", domain="Revelation", title="Scripture & Tradition", latin="Sacra Scriptura et Traditio",
        centralQuestion="Where does the Church hear the Word of God, and who may bind the conscience?",
        definition="Scripture and tradition name the means by which the apostolic faith is received, interpreted, and handed on. Their relation is among the deepest divides of the last five centuries.",
        lead="The canon itself is an act of the Church’s memory. Catholics and Orthodox refuse a Bible without that memory; classical Protestants refuse a tradition that can add dogmas beside Scripture.",
        questionQuote="Is tradition a second source, the living medium of the one source, or a fallible commentary on Scripture alone?",
        questionNote="All four traditions have a canon, creeds, and doctors. They clash over the rule of faith, the Magisterium, and whether ‘sola Scriptura’ is coherent.",
        deeperQuestions=["Who closed the canon?", "Can tradition define dogmas not explicit in Scripture?", "What is the deuterocanon / Anagignoskomena?", "How is private interpretation related to the Church?"],
        glance={"rows": glance_rows([
            ("Rule of faith", ["Scripture and apostolic tradition, interpreted by the Magisterium.", "Scripture within Holy Tradition (liturgy, Fathers, councils).", "Scripture as the only rule; creeds as faithful witnesses.", "Scripture as the only infallible rule; confessions subordinate."]),
            ("Canon", ["Includes deuterocanonical books.", "Septuagintal broader canon in use.", "Hebrew proto-canon as Old Testament; Apocrypha useful, not dogmatic.", "Hebrew proto-canon; apocrypha not canonical."]),
            ("Who interprets?", ["The teaching office of the bishops with the Pope.", "The Church in council and the consensus of the Fathers.", "Scripture interprets Scripture; the Church has ministerial authority.", "The Spirit speaking in Scripture; synods may err."]),
        ])},
        traditions=[
            trad("catholic", "Catholic", "One deposit; two modes; a living Magisterium.",
                 ["Dei verbum’s later language of a single deposit in two modes is anticipated by Trent: the Gospel is contained in written books and unwritten traditions. The Magisterium is not a third source but the authentic interpreter.",
                  "The canon including the deuterocanonicals is the Latin Old Testament. Private reading is encouraged; private judgment as a final court is refused."],
                 "The Church existed before the closed New Testament. A Bible without the Church that recognized it is an abstraction. John 16 and the Spirit’s leading of the apostles imply a living handing-on.",
                 "Protestants argue that this places an office above the Word. Orthodox accept tradition but reject a unique papal Magisterium.",
                 "Catholics reply that the Magisterium is servant of the Word, and that sola Scriptura historically multiplied rival ‘clear’ readings.",
                 [{"id": "irenaeus", "name": "Irenaeus"}, {"id": "aquinas", "name": "Thomas Aquinas"}, {"id": None, "name": "Council of Trent"}]),
            trad("orthodox", "Eastern Orthodox", "Holy Tradition as the life of the Spirit in the Church.",
                 ["Scripture is the heart of Tradition, not a rival to it. Liturgy, icons, canons, and the Fathers are organs of the same apostolic life. Ecumenical Councils are the dogmatic voice.",
                  "There is no papal oracle. Reception by the Church is part of a council’s authority. The Bible is never read as a bare text torn from worship."],
                 "Irenaeus’s rule of faith and the canon of truth show that Scripture and the Church’s preaching were born together. To isolate the book is to forget how we received it.",
                 "Catholics want a more precise living subject of infallibility. Protestants hear an uncritical sacralizing of custom.",
                 "Orthodoxy answers that the Spirit’s continuity is tested by catholicity across time—what was believed everywhere, always, by all—not by novelty or by a single see.",
                 [{"id": "irenaeus", "name": "Irenaeus"}, {"id": "athanasius", "name": "Athanasius"}, {"id": "basil", "name": "Basil"}]),
            trad("lutheran", "Lutheran", "Sola Scriptura with a catholic canon of interpretation.",
                 ["The Lutheran Reformation claimed Scripture as the only judge, source, and norm. Creeds and the Augsburg Confession are received as true expositions, not as a second Bible. The deuterocanon is read but not used to establish dogma.",
                  "Sola Scriptura was never meant as ‘me and my Bible in a vacuum’; it was a protest against binding the conscience by late medieval laws and uncertain traditions."],
                 "Christ and the apostles argue from Scripture. Human traditions may serve, but they cannot bind where the Word has not spoken, still less contradict it.",
                 "Catholics and Orthodox argue that the canon and Trinity themselves come through tradition. Reformed critics sometimes find Lutheranism too willing to keep ceremonies.",
                 "Lutherans distinguish apostolic tradition (which is the Gospel) from ecclesiastical tradition (which is judged by the Gospel). The creeds stand because they are scriptural, not vice versa.",
                 [{"id": "luther", "name": "Martin Luther"}, {"id": "melanchthon", "name": "Philip Melanchthon"}, {"id": None, "name": "Formula of Concord"}]),
            trad("reformed", "Reformed / Calvinist", "The only infallible rule.",
                 ["Westminster I is the classic Reformed statement: Scripture is sufficient, necessary, clear in things necessary to salvation, and self-authenticating by the Spirit. Councils and creeds have great weight and can err.",
                  "The regulative principle of worship (in many Reformed churches) applies sola Scriptura to the cultus more strictly than Lutheran ceremony does."],
                 "If any office can add dogma, the conscience has two masters. ‘To the law and to the testimony’ is the prophetic pattern.",
                 "The charge is historical: without tradition you cannot name the canon. The charge is practical: sola Scriptura yields endless division.",
                 "Reformed theology treats the canon as recognized, not conferred, and treats division as the cost of refusing a false unity around error.",
                 [{"id": "calvin", "name": "John Calvin"}, {"id": None, "name": "Westminster Confession"}, {"id": None, "name": "Helvetic Confessions"}]),
        ],
        agreements=["The Scriptures are the Word of God.", "The Church did not invent the Gospel.", "Creeds of Nicaea and Chalcedon are true.", "Not every custom is of equal weight.", "Christ is the center of Scripture."],
        clashes=[
            clash("I. Second source?", ["Yes: apostolic tradition with Scripture.", "Tradition is the living whole; Scripture its core.", "No: Scripture alone as rule.", "No: only infallible rule is Scripture."]),
            clash("II. Deuterocanon", ["Canonical.", "In liturgical use; broader canon.", "Useful, not dogmatic.", "Not canonical."]),
        ],
        timeline=[
            {"date": "c. 180", "title": "Irenaeus — rule of faith", "figureId": "irenaeus", "significance": "Scripture and the Church’s preaching against Gnostic secret tradition.", "extra": "Against Heresies III."},
            {"date": "367", "title": "Athanasius’s Festal Letter 39", "figureId": "athanasius", "significance": "Early list of the New Testament twenty-seven.", "extra": "New Advent, Canon of the New Testament."},
            {"date": "1546", "title": "Trent on Scripture and tradition", "figureId": None, "significance": "Latin canon and the two-mode handing-on.", "extra": "Session IV."},
            {"date": "16th–17th c.", "title": "Protestant confessions on Scripture", "figureId": "calvin", "significance": "Sola Scriptura as a confessional article.", "extra": "Formula of Concord SD Rule; Westminster I."},
        ],
        sources=[
            src("Catholic Encyclopedia", "Tradition and the Living Magisterium", "https://www.newadvent.org/cathen/15006b.htm", "New Advent"),
            src("Irenaeus", "Against Heresies III", "https://www.newadvent.org/fathers/0103.htm", "New Advent"),
            src("Athanasius", "Festal Letter 39", "https://www.newadvent.org/fathers/2809.htm", "New Advent"),
            src("Council of Trent", "Session IV", "https://www.newadvent.org/cathen/03274a.htm", "New Advent"),
            src("Formula of Concord", "Summary, Rule and Norm", "https://bookofconcord.org/", "Book of Concord"),
            src("Westminster Confession", "Chapter I", "https://www.ccel.org/ccel/schaff/creeds3.iv.xviii.html", "CCEL / Schaff"),
            src("John Calvin", "Institutes I.6–9", "https://www.ccel.org/ccel/calvin/institutes", "CCEL"),
        ],
        thread=[{"id": "scripture-tradition", "name": "Scripture & Tradition", "current": True},
                {"id": "church", "name": "Church"}, {"id": "trinity", "name": "Trinity"}],
        related=[{"id": "church", "name": "Church"}, {"id": "trinity", "name": "Trinity"},
                 {"id": "sacraments", "name": "Sacraments"}],
    )

    EXHIBITS["predestination"] = exhibit(
        id="predestination", domain="Salvation", title="Predestination", latin="Praedestinatio",
        centralQuestion="Does God’s eternal purpose choose some for salvation, and on what basis?",
        definition="Predestination concerns God’s eternal purpose in the movement of creatures toward their end. Christian traditions try to confess sovereignty without making God the author of sin or evacuating exhortation.",
        lead="Augustine, the medieval schools (Thomist and Molinist), Calvin, Arminius, Dort, and Eastern restraint form a map of one of theology’s sharpest inner conflicts.",
        questionQuote="Does God elect because He foresees faith, or is faith itself the fruit of election?",
        questionNote="All four traditions say God knows and rules. They clash over whether election is unconditional, whether there is a symmetric decree of reprobation, and how this is preached.",
        deeperQuestions=["Is election unconditional?", "Is reprobation a positive decree?", "Can the elect finally fall?", "How does this relate to Christ’s atonement?"],
        glance={"rows": glance_rows([
            ("Basis of election", ["God’s purpose; schools differ (Thomist / Molinist).", "Foreknowledge without a system that cancels synergy.", "Election to salvation in Christ; not a symmetric double decree.", "Unconditional election of the elect."]),
            ("Reprobation", ["God permits; does not positively will moral evil.", "Refusal is human; God is not the cause of sin.", "Restraint; many Lutherans refuse a decree to damnation.", "Preterition of the non-elect; infralapsarian vs supralapsarian schools."]),
            ("Perseverance", ["Gift of final perseverance, not automatically possessed.", "The path can be abandoned.", "The justified may fall; the elect will be kept in Lutheran tension.", "Perseverance of the saints."]),
        ])},
        traditions=[
            trad("catholic", "Catholic", "Predestination to life; God never authors sin.",
                 ["Catholic doctrine affirms predestination to glory as a free act of God and denies positive predestination to evil. Within that boundary, Thomists and Molinists have long disputed the mode of grace and foreknowledge.",
                  "The elect are known to God; the ordinary pastoral tone is exhortation, sacraments, and prayer for perseverance, not inspection of a secret list."],
                 "Romans 8–9 cannot be emptied of purpose. Yet James 1 and the whole of 1 Timothy 2.4 forbid making God the cause of sin or a respecter of persons who creates in order to damn.",
                 "Reformed critics say this is unstable: either grace is effectual or election rests on foreseen acts. Lutherans fear a hidden God behind the Gospel.",
                 "Catholic theology holds the antinomy pastorally: pray as if all depended on God, act as if all depended on the grace-enabled will—without a speculative decree of reprobation.",
                 [{"id": "augustine", "name": "Augustine"}, {"id": "aquinas", "name": "Thomas Aquinas"}, {"id": None, "name": "Council of Trent"}]),
            trad("orthodox", "Eastern Orthodox", "Foreknowledge, call, and unforced response.",
                 ["Eastern theology is wary of Western predestinarian systems. God desires the salvation of all. Election is preached as God’s purpose in Christ and His knowledge of who will freely receive, without a decree that cancels synergy.",
                  "The mystery of those who perish is referred to human refusal and to apophatic reserve, not to a positive will that they perish."],
                 "If God is love and the image includes freedom, a decree of reprobation as a mirror of election would make the Gospel a mask. 1 Timothy 2.4 is allowed to speak first.",
                 "Augustinians argue that this returns to a foreseen-faith scheme Paul rejects in Romans 9. Some Orthodox writers have under-read Augustine’s pastoral intent.",
                 "Orthodoxy prefers the liturgical confession of a God who ‘desires not the death of a sinner’ to a completed metaphysic of decrees.",
                 [{"id": "chrysostom", "name": "John Chrysostom"}, {"id": "maximus", "name": "Maximus the Confessor"}, {"id": "gregory-nyssa", "name": "Gregory of Nyssa"}]),
            trad("lutheran", "Lutheran", "Election in Christ; the revealed God of the Gospel.",
                 ["Luther can sound as absolute as any Augustinian in Bondage of the Will. The Formula of Concord XI then fences the doctrine: election is in Christ, unto salvation, a comfort; we are not to probe a hidden will to damnation as a symmetric decree.",
                  "The preached promise is universal. Double predestination as a system is typically refused as a Reformed overreach."],
                 "Election must be Gospel, or it becomes a new law of anxiety. We are to look to Christ, baptism, and the Word, not to a secret ledger.",
                 "Reformed theologians argue that a non-symmetric account is unstable. Catholics hear residual determinism in Luther’s earlier polemic.",
                 "Lutherans live with the tension: God is not the author of sin; the promise is for you; the hidden God is not a second gospel.",
                 [{"id": "luther", "name": "Martin Luther"}, {"id": "melanchthon", "name": "Philip Melanchthon"}, {"id": None, "name": "Formula of Concord"}]),
            trad("reformed", "Reformed / Calvinist", "Unconditional election and perseverance.",
                 ["Dort and Westminster teach election not based on foreseen faith, effectual calling, and perseverance. Reprobation is commonly preterition rather than a symmetric ‘creation unto damnation,’ though supralapsarian schools exist.",
                  "The pastoral use is assurance for those who look to Christ, and humility. The doctrine is not meant as a map of neighbors’ destinies."],
                 "If election rested on foreseen faith, faith would be the cause rather than the fruit. Romans 9 and Ephesians 1 press this hard.",
                 "The moral objection is perennial: this seems to make God partial and to freeze evangelism. Lutheran and Catholic objections target both symmetry and assurance-as-infallibility.",
                 "Reformed preaching of the free offer, and the distinction between the secret will and the revealed command, is the internal reply. Whether it succeeds remains the controversy.",
                 [{"id": "calvin", "name": "John Calvin"}, {"id": None, "name": "Synod of Dort"}, {"id": "augustine", "name": "Augustine"}]),
        ],
        agreements=["God’s knowledge is eternal.", "Salvation is not an accident.", "God is not the author of sin.", "Christ is the electing center of the New Testament.", "Presumption and despair are both pastoral evils."],
        clashes=[
            clash("I. Unconditional election?", ["Yes, as to predestination to life (schools differ on mode).", "Not as a decree cancelling synergy.", "Election to salvation in Christ; not a speculative double decree.", "Yes."]),
            clash("II. Perseverance of all the justified?", ["Final perseverance is a distinct gift.", "The path may be left.", "Falling from faith is possible.", "The elect persevere."]),
        ],
        timeline=[
            {"date": "c. 396–430", "title": "Augustine on predestination", "figureId": "augustine", "significance": "Western starting point, later read in rival ways.", "extra": "On the Predestination of the Saints."},
            {"date": "13th–16th c.", "title": "Thomist and Molinist schools", "figureId": "aquinas", "significance": "Catholic internal debate on grace and foreknowledge.", "extra": "ST I Q.23."},
            {"date": "1610–1619", "title": "Arminius and Dort", "figureId": "calvin", "significance": "Reformed definition against conditional election.", "extra": "Canons of Dort."},
            {"date": "1577", "title": "Formula of Concord XI", "figureId": "luther", "significance": "Lutheran fencing of election as Gospel comfort.", "extra": "Book of Concord."},
        ],
        sources=[
            src("Catholic Encyclopedia", "Predestination", "https://www.newadvent.org/cathen/12378a.htm", "New Advent"),
            src("Augustine", "On the Predestination of the Saints", "https://www.newadvent.org/fathers/15121.htm", "New Advent"),
            src("Thomas Aquinas", "ST I Q.23", "texts/summa.html?part=prima&q=23&a=1", "Predestination"),
            src("Formula of Concord", "Article XI", "https://bookofconcord.org/", "Book of Concord"),
            src("John Calvin", "Institutes III.21–24", "https://www.ccel.org/ccel/calvin/institutes", "CCEL"),
            src("John Chrysostom", "Homilies on Romans", "https://www.newadvent.org/fathers/2102.htm", "New Advent"),
        ],
        thread=[{"id": "grace", "name": "Grace"}, {"id": "free-will", "name": "Free Will"},
                {"id": "predestination", "name": "Predestination", "current": True}, {"id": "justification", "name": "Justification"}],
        related=[{"id": "grace", "name": "Grace"}, {"id": "free-will", "name": "Free Will"},
                 {"id": "atonement", "name": "Atonement"}, {"id": "original-sin", "name": "Original Sin"}],
    )

    EXHIBITS["faith-works"] = exhibit(
        id="faith-works", domain="Salvation", title="Faith & Works", latin="Fides et Opera",
        centralQuestion="How do trusting God and doing the good belong together?",
        definition="Faith and works names the question of how trust in God, obedience, love, and transformed action belong together. The tradition rejects a merely verbal faith while debating whether works enter the cause of justification.",
        lead="Paul and James, Augustine, Aquinas, Luther, Trent, and Wesley are one conversation. The slogan ‘faith alone’ is either the Gospel’s heart or a misunderstanding of living faith—depending on the tradition.",
        questionQuote="Do works help to justify, or only prove that justifying faith is alive?",
        questionNote="No classical tradition wants a faith that never loves. They clash over merit, the phrase sola fide, and the final judgment according to works.",
        deeperQuestions=["How to read Paul and James together?", "Is merit a biblical category?", "Does the final judgment make works a cause?", "Is ‘faith formed by charity’ still faith as Paul means it?"],
        glance={"rows": glance_rows([
            ("Instrument of justification", ["Faith formed by charity.", "Lived faith in synergy.", "Faith alone.", "Faith alone."]),
            ("Works", ["Meritorious in grace for increase and glory.", "The path of theosis.", "Necessary fruits, not causes.", "Necessary evidence, not ground."]),
            ("James 2", ["Works justify as the perfection of living faith.", "Faith without love is dead; the whole path saves.", "James unmasks a false faith; he does not add a second instrument.", "Same: evidential, not causal."]),
        ])},
        traditions=[
            trad("catholic", "Catholic", "Faith is the beginning; charity forms it; works in grace merit increase.",
                 ["Trent: faith is the beginning, foundation, and root. Yet faith without hope and charity does not perfectly unite to Christ. Works done in grace are truly meritorious—always as gifts, never as placing God in debt for the first justification.",
                  "The final judgment according to works is taken at face value as the manifestation and completion of a life of grace, not as a second, independent economy."],
                 "James 2, Matthew 25, and Paul on faith working through love will not let ‘faith’ mean a bare assent. To refuse merit language is to refuse that God crowns His own gifts.",
                 "Protestants hear a second justification by works and a loss of assurance. Some Orthodox find ‘merit’ too Latin even when they insist on ascesis.",
                 "Catholic replies: the first justification is unearned. Merit is participation, not a wage from nature. Assurance is hope, not a bare extra nos verdict isolated from love.",
                 [{"id": "augustine", "name": "Augustine"}, {"id": "aquinas", "name": "Thomas Aquinas"}, {"id": None, "name": "Council of Trent"}]),
            trad("orthodox", "Eastern Orthodox", "Faith lived: prayer, fasting, alms, the mysteries.",
                 ["Eastern preaching does not organize itself around sola fide. Faith is trust and fidelity, lived in the commandments and the liturgical year. Synergy holds belief and practice together without a Scholastic merit calculus.",
                  "The danger of quietism and the danger of moralism are both refused. Chrysostom’s homilies treat almsgiving as the test of faith without making God a debtor."],
                 "A faith that does not become love is not the faith of the apostles. The judgment scene in Matthew is the Church’s icon of this.",
                 "Protestants fear a slide into self-salvation. Catholics want more precise causal analysis. The East often declines both frames.",
                 "Orthodoxy answers by pointing to the publican and the pharisee: we work, and we confess that we are unprofitable servants.",
                 [{"id": "chrysostom", "name": "John Chrysostom"}, {"id": "basil", "name": "Basil"}, {"id": "maximus", "name": "Maximus the Confessor"}]),
            trad("lutheran", "Lutheran", "Faith alone justifies; faith is never alone.",
                 ["Augsburg IV–VI and XX: we are justified by faith apart from works of the law; yet this faith is bound to bring forth good works. Antinomianism is as false as work-righteousness.",
                  "The Formula of Concord distinguishes justification from sanctification without allowing a dead faith. James is an attack on hypocrisy, not a second article of justification."],
                 "If works enter the verdict, the conscience is back under law. Paul is then silenced. New obedience belongs to the justified life as fruit from a tree, not as a second root.",
                 "Catholics and Orthodox argue that this severs Paul from James and from the judgment according to works. Reformed critics usually agree on sola fide and then argue about law in the Christian life.",
                 "Lutherans preach the law fully to the Christian as well, but never as the ground of acceptance. Christ is the ground; works are the inevitable harvest of living faith.",
                 [{"id": "luther", "name": "Martin Luther"}, {"id": "melanchthon", "name": "Philip Melanchthon"}, {"id": None, "name": "Augsburg Confession"}]),
            trad("reformed", "Reformed / Calvinist", "Justification by faith; works as the evidence of union.",
                 ["Calvin’s Institutes III treats justification and sanctification as a double grace of union with Christ. Works never cause justification; they necessarily follow. The Westminster Confession XVI is careful: even our best works are imperfect, yet truly good as fruits of the Spirit.",
                  "The final judgment according to works is evidential and distributive of rewards, not a justification by a second law."],
                 "Paul’s ‘not of works’ would be emptied if works were a partial cause. James is speaking of a different ‘justification’—vindication of a faith already living.",
                 "The Catholic objection is that this makes James a verbal trick. Lutheranism shares sola fide but may differ on the third use of the law. Wesleyan Protestants later re-open cooperation after justification.",
                 "Reformed theology holds two things: the verdict is Christ’s righteousness, and the Spirit never justifies a faith that will not love.",
                 [{"id": "calvin", "name": "John Calvin"}, {"id": None, "name": "Westminster Confession"}, {"id": None, "name": "Heidelberg Catechism"}]),
        ],
        agreements=["Dead faith does not save.", "Paul and James are both Scripture.", "Christ is the meritorious cause of salvation.", "The justified life bears fruit.", "Boasting in unaided works is excluded."],
        clashes=[
            clash("I. Sola fide?", ["Rejected as Trent understood it.", "Not the native slogan; lived faith.", "The article by which the Church stands.", "The instrument of justification."]),
            clash("II. Merit of works in grace?", ["Yes, as God’s gifts crowned.", "Reward language without a Latin merit system.", "No meriting of justification; fruits only.", "No meriting of justification; rewards of grace possible."]),
        ],
        timeline=[
            {"date": "1st c.", "title": "Paul and James", "figureId": None, "significance": "The two canonical poles of the debate.", "extra": "Romans 3–5; Galatians 2; James 2."},
            {"date": "c. 413", "title": "Augustine, On Faith and Works", "figureId": "augustine", "significance": "Western insistence on a living faith.", "extra": "New Advent Fathers."},
            {"date": "1517–1547", "title": "Luther and Trent", "figureId": "luther", "significance": "Sola fide vs. faith formed by charity.", "extra": "The still-unresolved Reformation clash."},
        ],
        sources=[
            src("Catholic Encyclopedia", "Faith", "https://www.newadvent.org/cathen/05752c.htm", "New Advent"),
            src("Augustine", "On Faith and Works", "https://www.newadvent.org/fathers/1308.htm", "New Advent"),
            src("Thomas Aquinas", "ST I-II QQ.112–114", "texts/summa.html?part=prima-sec&q=114&a=1", "Merit"),
            src("Augsburg Confession", "Articles IV–VI, XX", "https://bookofconcord.org/augsburg-confession/", "Book of Concord"),
            src("John Calvin", "Institutes III.11–19", "https://www.ccel.org/ccel/calvin/institutes", "CCEL"),
            src("John Chrysostom", "Homilies on Romans", "https://www.newadvent.org/fathers/2102.htm", "New Advent"),
        ],
        thread=[{"id": "justification", "name": "Justification"}, {"id": "faith-works", "name": "Faith & Works", "current": True},
                {"id": "grace", "name": "Grace"}, {"id": "theosis", "name": "Theosis"}],
        related=[{"id": "justification", "name": "Justification"}, {"id": "grace", "name": "Grace"},
                 {"id": "predestination", "name": "Predestination"}, {"id": "sacraments", "name": "Sacraments"}],
    )

    EXHIBITS["incarnation"] = exhibit(
        id="incarnation", domain="Christ", title="Incarnation", latin="Incarnatio",
        centralQuestion="How is Jesus Christ true God and true man without confusion or division?",
        definition="The Incarnation is the confession that the eternal Son took flesh of the Virgin Mary and became man, remaining what He was, assuming what He was not, for us and for our salvation.",
        lead="Nicaea, Ephesus, and Chalcedon are the shared architecture. Remaining clashes are less about the definition than about its consequences: icons, the Theotokos, communicatio idiomatum, and whether fallen flesh was assumed.",
        questionQuote="What must be true of Christ’s humanity if God has truly come to save it?",
        questionNote="All four traditions are Chalcedonian (this archive does not treat non-Chalcedonian churches as a fifth column here). They clash over Mary’s title, images, and how properties of the natures are predicated of the one Person.",
        deeperQuestions=["Is Mary rightly called Theotokos?", "May Christ’s humanity be depicted?", "How do the two wills relate?", "Did the Son assume fallen flesh?"],
        glance={"rows": glance_rows([
            ("Definition", ["Chalcedon; later scholastic precision.", "Chalcedon; hypostatic union; theosis of the humanity.", "Chalcedon; communicatio idiomatum in Luther’s strong form.", "Chalcedon; careful extra Calvinisticum."]),
            ("Theotokos", ["Dogma (Ephesus); further Marian dogmas follow.", "Theotokos as the guard of the Incarnation.", "Theotokos confessed; later Marian dogmas refused.", "Theotokos as Christological; later cultus restrained."]),
            ("Images of Christ", ["Legitimate; Incarnation grounds sacred art.", "Icons as theology in color; Seventh Council.", "Art permitted; not a dogmatic system of icons.", "Often more reserved; some Reformed streams iconoclastic."]),
        ])},
        traditions=[
            trad("catholic", "Catholic", "One Person, two natures; Mary as Theotokos.",
                 ["Catholic Christology is Chalcedonian and then scholastic: the hypostatic union, two wills, the communication of idioms. Ephesus’s Theotokos is the hinge. Later Catholic Marian dogmas (Immaculate Conception, Assumption) are developments the other three traditions do not share.",
                  "The Incarnation is the ground of sacramental realism and of sacred images."],
                 "What is not assumed is not healed (Gregory Nazianzen). A merely moral union (Nestorius as received) cannot save; a fusion of natures (Eutyches as received) cannot leave us human.",
                 "Orthodoxy shares Chalcedon but rejects later papal Marian definitions. Protestants fear that Theotokos-devotion becomes a rival mediation.",
                 "Catholics distinguish hyperdulia from latria and insist every Marian dogma is a Christological fence, not a second gospel.",
                 [{"id": "athanasius", "name": "Athanasius"}, {"id": "aquinas", "name": "Thomas Aquinas"}, {"id": None, "name": "Council of Chalcedon"}]),
            trad("orthodox", "Eastern Orthodox", "The Word became flesh that we might become god by grace.",
                 ["The Incarnation is the beginning of theosis. Maximus’s dyothelitism protects a real human will in Christ. Icons of Christ are a confession of the Incarnation (Nicaea II).",
                  "Theotokos is non-negotiable. The humanity is deified without ceasing to be human."],
                 "If the flesh of Christ cannot be depicted, the Incarnation is treated as a phantom. The Seventh Council is therefore a Christological council.",
                 "Reformed iconoclasm hears a violation of the second commandment. Some Western scholastics pressed questions the East leaves in mystery.",
                 "Orthodoxy answers that the commandment forbade idols of what is not God; the icon of Christ is possible only because God has a human face.",
                 [{"id": "athanasius", "name": "Athanasius"}, {"id": "maximus", "name": "Maximus the Confessor"}, {"id": "gregory-nazianzen", "name": "Gregory Nazianzen"}]),
            trad("lutheran", "Lutheran", "The finite is capable of the infinite.",
                 ["Lutheran Christology presses the communication of attributes so that Christ’s humanity shares in divine majesty (ubiquity in the Supper debate). Theotokos is confessed. Later Roman Marian dogmas are refused as unbound by Scripture.",
                  "The Incarnation is the pattern of the means of grace: God hidden in lowly things."],
                 "If Christ’s body cannot be where He promises it, the union is too weak. ‘The Word became flesh’ authorizes both the manger and the altar.",
                 "Reformed theology charges a Eutychian leakage of properties. Catholics share much Christology then add Marian developments Lutherans will not carry.",
                 "Lutherans distinguish the genus maiestaticum from a mixing of essences. The man Christ is omnipresent not as a second divinity but by the union.",
                 [{"id": "luther", "name": "Martin Luther"}, {"id": None, "name": "Formula of Concord VIII"}, {"id": "athanasius", "name": "Athanasius"}]),
            trad("reformed", "Reformed / Calvinist", "True God, true man; the extra Calvinisticum.",
                 ["The Reformed extra holds that the Son is fully united to the flesh yet not confined to it. This protects both natures and underwrites a heavenly location of Christ’s body in the Supper debate.",
                  "Theotokos may be used Christologically. Images of God, including many images of Christ, are treated with second-commandment severity in classical Reformed churches."],
                 "If the Word is shut up in the flesh, He is no longer the Logos who fills heaven and earth. Distinction of natures is the only way to keep a real humanity.",
                 "Lutherans hear a Nestorian gap. The East hears iconoclasm as a denial of the Incarnation’s visibility.",
                 "Reformed theology claims Chalcedon as its own: unconfused, unchanged, undivided, unseparated—and therefore not locally enclosed in bread or in a panel.",
                 [{"id": "calvin", "name": "John Calvin"}, {"id": None, "name": "Chalcedon"}, {"id": "athanasius", "name": "Athanasius"}]),
        ],
        agreements=["Jesus Christ is true God and true man.", "There is one Person of the Word.", "Nicaea and Chalcedon are true.", "The Incarnation is for our salvation.", "Docetism and Arianism are heresy."],
        clashes=[
            clash("I. Images of Christ", ["Yes; sacred art.", "Yes; icons as dogma in color.", "Permitted; not Nicaea II as a Reformation article.", "Classically restricted."]),
            clash("II. How the properties are shared", ["Scholastic communicatio.", "Deification of the humanity.", "Strong Lutheran genus maiestaticum.", "Extra Calvinisticum; restrained communication."]),
        ],
        timeline=[
            {"date": "325 / 431 / 451", "title": "Nicaea, Ephesus, Chalcedon", "figureId": "athanasius", "significance": "Homoousios, Theotokos, two natures.", "extra": "The shared dogmatic spine."},
            {"date": "681", "title": "Constantinople III", "figureId": "maximus", "significance": "Two wills in Christ.", "extra": "Maximus against monothelitism."},
            {"date": "787", "title": "Nicaea II", "figureId": None, "significance": "Icons as a consequence of the Incarnation.", "extra": "Still a live Reformed–Orthodox clash."},
        ],
        sources=[
            src("Catholic Encyclopedia", "Incarnation", "https://www.newadvent.org/cathen/07706b.htm", "New Advent"),
            src("Athanasius", "On the Incarnation", "https://www.newadvent.org/fathers/2802.htm", "New Advent"),
            src("Gregory Nazianzen", "Epistle 101", "https://www.newadvent.org/fathers/3103.htm", "New Advent"),
            src("Thomas Aquinas", "ST III QQ.1–26", "texts/summa.html?part=tertia&q=1&a=1", "The Incarnation"),
            src("Formula of Concord", "Article VIII", "https://bookofconcord.org/", "Book of Concord"),
            src("John Calvin", "Institutes II.12–14", "https://www.ccel.org/ccel/calvin/institutes", "CCEL"),
        ],
        thread=[{"id": "trinity", "name": "Trinity"}, {"id": "incarnation", "name": "Incarnation", "current": True},
                {"id": "atonement", "name": "Atonement"}, {"id": "theosis", "name": "Theosis"}],
        related=[{"id": "trinity", "name": "Trinity"}, {"id": "atonement", "name": "Atonement"},
                 {"id": "eucharist", "name": "Eucharist"}, {"id": "theosis", "name": "Theosis"}],
    )

    EXHIBITS["baptism"] = exhibit(
        id="baptism", domain="Sacraments", title="Baptism", latin="Baptismus",
        centralQuestion="What does baptism do, and whom is it for?",
        definition="Baptism is the washing with water in the triune Name by which a person is bound to Christ’s death and resurrection. Traditions differ over regeneration, infant baptism, and whether it can be repeated.",
        lead="The New Testament, the early catechumenate, Augustine against the Donatists, and the Reformation’s infant-baptism consensus (with later Baptist dissent outside these four columns) make baptism both a shared rite and a loaded one.",
        questionQuote="Is baptism God’s act of new birth, or the believer’s public pledge—or both, in a certain order?",
        questionNote="Catholic, Orthodox, Lutheran, and classical Reformed churches all baptize infants. They still clash over what the water does, and over rebaptism of heretics.",
        deeperQuestions=["Does baptism regenerate?", "Why baptize infants?", "Is immersion required?", "Can heretical baptism be valid?"],
        glance={"rows": glance_rows([
            ("Effect", ["Regeneration; remission of original and actual sin.", "Illumination, new birth, gift of the Spirit with chrismation.", "Baptismal regeneration by the Word in the water.", "Sign and seal of regeneration; Spirit not bound to the moment."]),
            ("Infants", ["Yes; they receive grace.", "Yes; they are born into the Church.", "Yes; they are included in the promise.", "Yes; covenant children receive the sign."]),
            ("Rebaptism", ["No; character indelible. Conditional baptism if doubt.", "No; one baptism. Economy for some cases.", "No; one baptism for the remission of sins.", "No; one baptism; irregular baptisms examined."]),
        ])},
        traditions=[
            trad("catholic", "Catholic", "The sacrament of regeneration and the door of the Church.",
                 ["Baptism remits original sin and actual sins, infuses sanctifying grace, and imprints an indelible character. It is ordinarily necessary. Infant baptism is apostolic practice as the Latin West reads it. Trinitarian heretical baptism may be valid as to character (Augustine vs. Donatists; later canon law).",
                  "Conditional baptism is used when previous baptism is doubtful. It is not a second baptism."],
                 "John 3, Acts 2.38, Titus 3.5, and the Church’s unbroken infant practice imply that God does something in the water, not merely that we signal something already complete.",
                 "Reformed caution about presuming regeneration in every baptized infant, and later Baptist rejection of infant baptism, press the question of faith’s role.",
                 "Catholic theology holds that infants receive grace without an adult act of faith, and that adults must not place an obstacle. God is the agent.",
                 [{"id": "augustine", "name": "Augustine"}, {"id": "aquinas", "name": "Thomas Aquinas"}, {"id": None, "name": "Council of Trent"}]),
            trad("orthodox", "Eastern Orthodox", "Burial and resurrection with Christ; chrismation follows.",
                 ["Baptism is death and resurrection with Christ, typically by immersion, immediately followed by chrismation and communion even for infants. It is illumination. There is one baptism; reception of converts uses acrivia or economia.",
                  "The rite is the Church’s birthing. Private symbolic interpretations are refused."],
                 "Romans 6 is not a metaphor hanging in the air; it is enacted in the font. Infants are not waiting outside the Kingdom until they can lecture on doctrine.",
                 "Latin character-theology and Reformed delayed-communion of infants both look like fragmenting the one initiation.",
                 "Orthodoxy keeps baptism, chrism, and first communion as one complex of initiation, judging later Western splits as a loss of mystagogy.",
                 [{"id": "chrysostom", "name": "John Chrysostom"}, {"id": None, "name": "Cyril of Jerusalem"}, {"id": "basil", "name": "Basil"}]),
            trad("lutheran", "Lutheran", "Water joined to the Word: a washing of regeneration.",
                 ["Luther’s Small Catechism: baptism works forgiveness, delivers from death and the devil, and gives eternal salvation to all who believe it—as the words and promises of God declare. Infants are baptized because the promise includes them and they are capable of faith as God’s work.",
                  "It is not the water that does it, but the Word of God in and with the water."],
                 "‘Baptism now saves you’ (1 Peter 3.21) must be allowed to stand. To make baptism a mere badge of our prior decision is to invert Gospel into law.",
                 "Reformed partners worry about ex opere regeneration of infants who later fall. Catholics want a more ontological ‘character.’ Baptists reject the infant premise.",
                 "Lutherans locate the power in the promise, and treat later unbelief as rejection of a gift truly given, not as proof that nothing was given.",
                 [{"id": "luther", "name": "Martin Luther"}, {"id": "melanchthon", "name": "Philip Melanchthon"}, {"id": None, "name": "Small Catechism"}]),
            trad("reformed", "Reformed / Calvinist", "The covenant sign and seal.",
                 ["Baptism is a sign and seal of ingrafting into Christ, of regeneration and remission—administered to believers and their children. It does not automatically regenerate at the moment in every case; the Spirit’s timing is His own. Yet it is not a bare badge.",
                  "Westminster 28 and the Heidelberg Catechism frame infant baptism federally rather than by a Lutheran ‘infants can believe’ emphasis."],
                 "Abraham’s covenant included children before they could confess. Baptism is the New Testament circumcision (Col. 2), not a reward for a mature decision.",
                 "Lutherans hear a weakening of ‘baptism saves.’ Catholics hear a denial of instrumental causality. Credobaptists hear an invalid analogy with circumcision.",
                 "Reformed theology holds both the objectivity of the covenant sign and the necessity of personal faith in due time, without making the sign empty.",
                 [{"id": "calvin", "name": "John Calvin"}, {"id": None, "name": "Heidelberg Catechism"}, {"id": None, "name": "Westminster Confession"}]),
        ],
        agreements=["Baptism is in the triune Name.", "It is once for all.", "It binds to Christ’s death and resurrection.", "It is Christ’s institution, not a human extra.", "Infant baptism is the classical practice of these four traditions."],
        clashes=[
            clash("I. Regenerates at the font?", ["Yes, if no obstacle.", "Yes; illumination and new birth.", "Yes, by the Word in the water.", "Seals regeneration; timing of the Spirit may differ."]),
            clash("II. Immediate chrismation and communion of infants", ["Confirmation usually later in the Latin West.", "Yes; one initiation.", "Confirmation a later catechetical rite; communion practices vary.", "Communion after profession of faith typically."]),
        ],
        timeline=[
            {"date": "2nd–4th c.", "title": "Catechumenate and infant baptism", "figureId": None, "significance": "Both adult and infant practice attested.", "extra": "Hippolytus; Origen; Cyprian; Augustine."},
            {"date": "c. 400–411", "title": "Augustine vs the Donatists", "figureId": "augustine", "significance": "Validity of baptism outside a schismatic group.", "extra": "On Baptism."},
            {"date": "1529 / 1547", "title": "Luther’s Catechism and Trent", "figureId": "luther", "significance": "Reformation and Catholic definitions of baptismal grace.", "extra": "Small Catechism; Trent Session VII."},
        ],
        sources=[
            src("Catholic Encyclopedia", "Baptism", "https://www.newadvent.org/cathen/02258b.htm", "New Advent"),
            src("Augustine", "On Baptism", "https://www.newadvent.org/fathers/1408.htm", "New Advent"),
            src("Cyril of Jerusalem", "Catechetical Lectures", "https://www.newadvent.org/fathers/3101.htm", "New Advent"),
            src("Martin Luther", "Small Catechism — Baptism", "https://bookofconcord.org/small-catechism/", "Book of Concord"),
            src("John Calvin", "Institutes IV.15–16", "https://www.ccel.org/ccel/calvin/institutes", "CCEL"),
            src("Thomas Aquinas", "ST III QQ.66–71", "texts/summa.html?part=tertia&q=66&a=1", "On baptism"),
        ],
        thread=[{"id": "original-sin", "name": "Original Sin"}, {"id": "baptism", "name": "Baptism", "current": True},
                {"id": "sacraments", "name": "Sacraments"}, {"id": "grace", "name": "Grace"}],
        related=[{"id": "original-sin", "name": "Original Sin"}, {"id": "sacraments", "name": "Sacraments"},
                 {"id": "eucharist", "name": "Eucharist"}, {"id": "church", "name": "Church"}],
    )

    EXHIBITS["theosis"] = exhibit(
        id="theosis", domain="Salvation", title="Theosis", latin="Deificatio",
        centralQuestion="In what sense do the redeemed ‘become god’?",
        definition="Theosis (deification) is participation in the divine life: the redeemed are made partakers of the divine nature without becoming a fourth person of the Trinity or losing creaturehood.",
        lead="Athanasius’s dictum is quoted East and West. The clash is whether theosis is the governing name for salvation, and whether Palamas’s essence–energies distinction is required to keep it from pantheism.",
        questionQuote="Can creatures share in God’s life without sharing God’s essence?",
        questionNote="2 Peter 1.4 is canonical for all. They clash over Palamism, created grace, and whether forensic justification can sit inside a theosis frame.",
        deeperQuestions=["Essence or energies?", "Is theosis the same as sanctification?", "Does it begin in baptism or only at the end?", "Is Palamas a dogma or a school?"],
        glance={"rows": glance_rows([
            ("Governing name", ["Sanctifying grace and the light of glory; theosis language used.", "Theosis as the goal of the whole economy.", "Sanctification and resurrection; theosis language cautious.", "Glorification and union with Christ; theosis language cautious."]),
            ("How participation works", ["Created habitual grace; beatific vision of the essence.", "Uncreated energies; essence incommunicable.", "New birth and resurrection of the body.", "Union with Christ; Spirit’s indwelling."]),
            ("Relation to justification", ["Includes inner renewal.", "Not a separate forensic article.", "Distinct from forensic justification.", "Distinct; follows in the ordo."]),
        ])},
        traditions=[
            trad("catholic", "Catholic", "Partakers of the divine nature by sanctifying grace.",
                 ["Catholic theology reads 2 Peter 1.4 as real participation. Sanctifying grace is a created gift making the soul pleasing to God; the blessed will see God by the light of glory. The language of deification is patristic and liturgical, even when the Latin system prefers ‘grace’ and ‘vision.’",
                  "Aquinas: the blessed see the divine essence; that is the terminus. Palamite energies are not the native Latin tool, though modern Catholic–Orthodox dialogue has narrowed some gaps."],
                 "If the end is only forensic acquittal, adoption and the indwelling Spirit are under-explained. The Incarnation aims at communion, not merely a cleared docket.",
                 "Orthodoxy fears created grace as a screen. Protestants fear a confusion of Creator and creature and a sliding of justification into process.",
                 "Catholics insist created grace is not a thing between us and God that blocks Him; it is God’s way of elevating the creature without absorbing it.",
                 [{"id": "athanasius", "name": "Athanasius"}, {"id": "aquinas", "name": "Thomas Aquinas"}, {"id": "augustine", "name": "Augustine"}]),
            trad("orthodox", "Eastern Orthodox", "Uncreated grace; the vision of the light.",
                 ["Theosis is the name of salvation. Palamas, against Barlaam, distinguished the incommunicable essence from the uncreated energies that are truly God and truly shared. Hesychast prayer and the liturgical life are the ordinary path.",
                  "Baptism begins deification; it is not postponed to an afterlife verdict."],
                 "Without the essence–energies distinction, one must either deny real participation or swallow pantheism. The Transfiguration is the icon of what is offered.",
                 "Latin scholastics historically charged Palamism with composing God. Protestants hear mysticism unmoored from justification.",
                 "Orthodoxy answers that the distinction is how the Fathers already spoke, and that theosis includes repentance, not a bypass of the Cross.",
                 [{"id": "athanasius", "name": "Athanasius"}, {"id": "palamas", "name": "Gregory of Palamas"}, {"id": "maximus", "name": "Maximus the Confessor"}]),
            trad("lutheran", "Lutheran", "Union with Christ; caution about ‘becoming god.’",
                 ["Luther can speak of a happy exchange so intimate that the soul is one with Christ. Later Lutheran orthodoxy is more reserved about theosis as a slogan, insisting that justification remain forensic and that the Creator–creature line not blur.",
                  "The resurrection of the body, not an essence-vision system, is the public hope."],
                 "The danger of theosis-language is a theology of glory that skips the Cross. Christ for us must remain first; Christ in us follows.",
                 "The East hears a truncated salvation. Some Finnish Lutheran scholarship has reopened Luther’s participation language, itself contested.",
                 "Lutherans can admit real union and even patristic theosis phrases while refusing to let them replace the article of justification.",
                 [{"id": "luther", "name": "Martin Luther"}, {"id": None, "name": "Formula of Concord"}, {"id": "athanasius", "name": "Athanasius"}]),
            trad("reformed", "Reformed / Calvinist", "Union with Christ and glorification.",
                 ["Calvin’s union with Christ is as central as any theosis doctrine, yet he refuses a mixing of substances. Glorification is the terminus of the ordo. 2 Peter 1.4 is read as covenant fellowship and moral transformation, not Palamite vision.",
                  "The extra Calvinisticum again: God is with us without ceasing to be God, and we are in God without ceasing to be creatures."],
                 "Participation must be real enough to save and modest enough to remain worship. Union is federal, mystical, and sanctifying—not essential.",
                 "Palamite Orthodoxy hears a refusal of the uncreated light. Catholics hear an under-ontological grace. Some Reformed mystics (later) press further than the confessions.",
                 "Reformed theology treats deification-language as dangerous unless constantly glossed as communion, not as becoming what God is.",
                 [{"id": "calvin", "name": "John Calvin"}, {"id": None, "name": "Westminster Confession"}, {"id": "athanasius", "name": "Athanasius"}]),
        ],
        agreements=["Creatures never become a fourth divine Person.", "2 Peter 1.4 is true.", "The goal is communion with God.", "The Incarnation makes participation possible.", "Pantheism is false."],
        clashes=[
            clash("I. Essence–energies?", ["Not the Latin system; beatific vision of the essence.", "Required for real participation.", "Not a Lutheran dogma.", "Not a Reformed dogma."]),
            clash("II. Is theosis the name of salvation?", ["One valid name among grace, vision, charity.", "The governing name.", "Secondary to justification.", "Secondary to justification and glorification."]),
        ],
        timeline=[
            {"date": "c. 318", "title": "Athanasius — On the Incarnation", "figureId": "athanasius", "significance": "God became man that we might become god.", "extra": "The sentence all later parties quote."},
            {"date": "7th c.", "title": "Maximus", "figureId": "maximus", "significance": "Theosis as the logos of creatures fulfilled.", "extra": "Ambigua; Questions to Thalassius."},
            {"date": "14th c.", "title": "Palamite councils", "figureId": "palamas", "significance": "Essence–energies as Orthodox dogma.", "extra": "Still the East–West metaphysical clash."},
        ],
        sources=[
            src("Athanasius", "On the Incarnation", "https://www.newadvent.org/fathers/2802.htm", "New Advent"),
            src("Catholic Encyclopedia", "Supernatural Gift / Grace", "https://www.newadvent.org/cathen/06689x.htm", "New Advent"),
            src("Thomas Aquinas", "ST I-II Q.110; I Q.12", "texts/summa.html?part=prima&q=12&a=1", "Vision of God"),
            src("John Calvin", "Institutes III.1–3, 25", "https://www.ccel.org/ccel/calvin/institutes", "CCEL"),
            src("Basil", "On the Holy Spirit", "https://www.newadvent.org/fathers/3203.htm", "New Advent"),
        ],
        thread=[{"id": "incarnation", "name": "Incarnation"}, {"id": "theosis", "name": "Theosis", "current": True},
                {"id": "grace", "name": "Grace"}, {"id": "justification", "name": "Justification"}],
        related=[{"id": "grace", "name": "Grace"}, {"id": "incarnation", "name": "Incarnation"},
                 {"id": "holy-spirit", "name": "Holy Spirit"}, {"id": "justification", "name": "Justification"}],
    )

    EXHIBITS["holy-spirit"] = exhibit(
        id="holy-spirit", domain="God", title="Holy Spirit", latin="Spiritus Sanctus",
        centralQuestion="Who is the Holy Spirit, and how does He act in the Church and in salvation?",
        definition="The Holy Spirit is the third Person of the Trinity, Lord and Giver of life, who proceeds from the Father (the East adds: not from the Son as from a second source; the West adds: and the Son), and who is sent in the economy to sanctify, indwell, and gift the Church.",
        lead="The Creed of 381 is shared. The Filioque, confirmation/chrismation, and the relation of Spirit to Word and sacrament are the remaining live arguments among these four.",
        questionQuote="Does the Spirit proceed from the Father alone, and does He work apart from the instituted means?",
        questionNote="All four reject a merely impersonal force. They clash over procession, chrismation, and whether the Spirit is bound to Word and sacrament.",
        deeperQuestions=["Filioque?", "Is chrismation a distinct sacrament of the Spirit?", "Does the Spirit ordinarily work through means?", "How are charisms related to office?"],
        glance={"rows": glance_rows([
            ("Procession", ["From the Father and the Son.", "From the Father alone.", "Western Filioque retained.", "Western Filioque retained."]),
            ("How He is given", ["Baptism, confirmation, Eucharist, charisms in the Church.", "Chrismation with baptism; mysteries and ascesis.", "Word and Sacrament; no separate confirmation-as-sacrament required.", "Word and sacrament as means; inner testimony of the Spirit."]),
            ("Relation to Scripture", ["Spirit in the Magisterium and in the inspired text.", "Spirit in Tradition and liturgy.", "Spirit bound to the external Word, against Enthusiasts.", "Spirit speaking in Scripture; inner testimony confirms."]),
        ])},
        traditions=[
            trad("catholic", "Catholic", "The Lord and Giver of life; Filioque; sevenfold gifts.",
                 ["Latin pneumatology follows the Creed with the Filioque, Augustine’s mutual-love analogy, and a developed theology of gifts, fruits, and confirmation as a distinct sacrament completing baptismal grace.",
                  "The Spirit is the soul of the Church, not a private oracle against her."],
                 "John 15–16 and the sending of the Spirit from the risen Christ reveal an eternal origin involving the Son. Confirmation is the personal sealing of that gift.",
                 "The East rejects the Filioque’s insertion and the splitting of initiation. Protestants reject confirmation as a sacrament and a Magisterium that claims the Spirit’s voice.",
                 "Catholics distinguish the Father’s monarchy from a denial of the Son’s role, and treat confirmation as Christ’s gift, not a human extra.",
                 [{"id": "augustine", "name": "Augustine"}, {"id": "basil", "name": "Basil"}, {"id": "aquinas", "name": "Thomas Aquinas"}]),
            trad("orthodox", "Eastern Orthodox", "The Spirit from the Father; chrismation; epiclesis.",
                 ["The Creed of 381 without addition is the dogmatic norm. Chrismation immediately follows baptism. The epiclesis in the Liturgy names the Spirit’s act in the mysteries. Palamas’s energies include the Spirit’s uncreated work in theosis.",
                  "Private ‘Spirit against the Church’ movements are treated as a Western illness."],
                 "The monarchy of the Father is the only safe account of unity. The Spirit is not a junior deity proceeding from two sources.",
                 "The West hears a denial of the Son. Some Orthodox polemics have over-claimed that Filioque caused every later Western error.",
                 "Orthodoxy distinguishes the Spirit’s economic mission through the Son from eternal procession from the Father alone.",
                 [{"id": "basil", "name": "Basil"}, {"id": "gregory-nazianzen", "name": "Gregory Nazianzen"}, {"id": "palamas", "name": "Gregory of Palamas"}]),
            trad("lutheran", "Lutheran", "The Spirit bound to the Word.",
                 ["Luther’s battle with Enthusiasts set a lasting rule: the Spirit does not work savingly apart from the external Word and the sacraments. The Filioque is retained. Confirmation is a useful catechetical rite, not a second biblical sacrament required for the Spirit.",
                  "The Spirit creates faith, sanctifies, and keeps the Church in the truth of the Gospel."],
                 "A Spirit who floats free of the Word cannot be tested and becomes a new law of inner experiences. ‘Faith comes by hearing.’",
                 "Pentecostal later movements (outside this fourfold map) reject the ‘bound to means’ thesis. The East rejects the Filioque. Reformed partners share much and then argue about the Supper.",
                 "Lutherans do not imprison the Spirit; they confess where He has promised to be found.",
                 [{"id": "luther", "name": "Martin Luther"}, {"id": "basil", "name": "Basil"}, {"id": None, "name": "Augsburg Confession"}]),
            trad("reformed", "Reformed / Calvinist", "The inner testimony and the means of grace.",
                 ["Calvin’s inner testimony of the Spirit authenticates Scripture to the believer. The Spirit applies redemption, regenerates, and indwells. He is not bound as a prisoner of the sacraments, yet He ordinarily uses Word and sacrament.",
                  "Filioque is generally retained. Extraordinary charisms are not the marks of the Church in classical confessions."],
                 "Without the Spirit, the Word is a dead letter; without the Word, ‘Spirit’ is a name for our enthusiasm. Both must be held.",
                 "Lutherans fear a gap between sign and Spirit. The East fears the Filioque. Catholics fear a private testimony replacing the Church.",
                 "Reformed theology locates the Spirit’s freedom in election and application, and His reliability in the promised means.",
                 [{"id": "calvin", "name": "John Calvin"}, {"id": "basil", "name": "Basil"}, {"id": None, "name": "Westminster Confession"}]),
        ],
        agreements=["The Holy Spirit is God.", "He is a Person, not a force.", "He spoke by the prophets.", "He is the Giver of life and of the Church’s unity.", "Blasphemy against the Spirit is a real warning."],
        clashes=[
            clash("I. Filioque", ["Confessed.", "Rejected.", "Confessed.", "Confessed."]),
            clash("II. Bound to Word and sacrament?", ["Ordinary means; not exclusive of extra-sacramental grace.", "Mysteries and ascesis; not Enthusiast interiority.", "Savingly bound to the external Word.", "Ordinarily through means; inwardly in regeneration."]),
        ],
        timeline=[
            {"date": "381", "title": "Constantinople I", "figureId": "basil", "significance": "The Spirit confessed as Lord and Giver of life.", "extra": "Basil’s On the Holy Spirit prepared the ground."},
            {"date": "late 4th–5th c.", "title": "Augustine on the Spirit", "figureId": "augustine", "significance": "Latin Filioque theology takes shape.", "extra": "De Trinitate."},
            {"date": "1520s", "title": "Luther vs the Enthusiasts", "figureId": "luther", "significance": "Spirit bound to the external Word.", "extra": "A lasting Lutheran–Reformed family trait."},
        ],
        sources=[
            src("Catholic Encyclopedia", "Holy Ghost", "https://www.newadvent.org/cathen/07409a.htm", "New Advent"),
            src("Basil", "On the Holy Spirit", "https://www.newadvent.org/fathers/3203.htm", "New Advent"),
            src("Augustine", "On the Trinity", "https://www.newadvent.org/fathers/1301.htm", "New Advent"),
            src("Augsburg Confession", "Article V", "https://bookofconcord.org/augsburg-confession/", "Book of Concord"),
            src("John Calvin", "Institutes I.13; III.1", "https://www.ccel.org/ccel/calvin/institutes", "CCEL"),
            src("Catholic Encyclopedia", "Filioque", "https://www.newadvent.org/cathen/06073a.htm", "New Advent"),
        ],
        thread=[{"id": "trinity", "name": "Trinity"}, {"id": "holy-spirit", "name": "Holy Spirit", "current": True},
                {"id": "grace", "name": "Grace"}, {"id": "theosis", "name": "Theosis"}],
        related=[{"id": "trinity", "name": "Trinity"}, {"id": "grace", "name": "Grace"},
                 {"id": "sacraments", "name": "Sacraments"}, {"id": "scripture-tradition", "name": "Scripture & Tradition"}],
    )
    return EXHIBITS
