def add_rest(EXHIBITS):
    EXHIBITS["trinity"] = exhibit(
        id="trinity", domain="God", title="Trinity", latin="Trinitas",
        centralQuestion="How is the one God Father, Son, and Holy Spirit?",
        definition="The Trinity is the Christian confession that the one God exists eternally as Father, Son, and Holy Spirit: distinct in person, one in divine being, revealed in the economy of salvation.",
        lead="The Nicene faith is shared. The principal intra-Christian clash is the Filioque and the monarchy of the Father; Reformation churches receive the Western creed while rejecting later anti-trinitarian movements.",
        questionQuote="Can the Church say ‘three’ without dividing God, and ‘one’ without confusing the persons?",
        questionNote="All four traditions reject Arianism, modalism, and tritheism. The remaining arguments are about procession, analogy, and the limits of speech.",
        deeperQuestions=["How are ousia and hypostasis distinguished?", "Does the Spirit proceed from the Father alone, or from the Father and the Son?", "What does the Father’s monarchy mean?", "How far may psychological analogies be pressed?"],
        glance={"rows": glance_rows([
            ("Unity and distinction", ["One essence, three persons; relations of origin.", "One essence, three hypostases; monarchy of the Father.", "Nicene and Athanasian Creeds received.", "Nicene faith; Western Filioque typically retained."]),
            ("Filioque", ["Spirit proceeds from Father and Son.", "Rejected as unauthorized and theologically risky.", "Retained with the Latin West.", "Retained; some later Reformed revisit the dispute."]),
            ("Analogy", ["Augustine’s mind; Scholastic relations.", "Apophatic restraint; Cappadocian taxis.", "Creeds over speculation.", "Creeds and Institutes I.13; modest analogy."]),
        ])},
        traditions=[
            trad("catholic", "Catholic", "One essence in three persons; Filioque.",
                 ["Latin theology, following Augustine and the medieval schools, develops relational analysis of the processions. The Filioque is confessed as safeguarding the Son’s full divinity in the Spirit’s origin.",
                  "Aquinas’s treatise (ST I QQ.27–43) remains the standard Scholastic map of processions, relations, and missions."],
                 "If the Spirit did not proceed from the Son as from the Father, the Son’s homoousion in the inner life of God would be obscured. The West reads John 16 and the sending of the Spirit as revealing eternal origin.",
                 "The East charges an unauthorized creed change and a risk of subordinating the Spirit or collapsing the taxis of the persons.",
                 "Catholics distinguish the Father as principium sine principio from the Son as principium de principio, claiming the monarchy is preserved.",
                 [{"id": "augustine", "name": "Augustine"}, {"id": "aquinas", "name": "Thomas Aquinas"}, {"id": None, "name": "Nicene Creed"}]),
            trad("orthodox", "Eastern Orthodox", "Monarchy of the Father; Spirit from the Father.",
                 ["The Cappadocian settlement: one ousia, three hypostases. The Father is the sole unoriginate source. The Filioque is rejected as an addition that disturbs the taxis.",
                  "Worship and apophatic theology accompany precise formulas. The Creed of 381 is the dogmatic norm."],
                 "The monarchy of the Father is the guarantee of unity. Two sources of the Spirit would threaten either two Gods or a blurred Spirit.",
                 "The West hears a denial of the Son’s role in the Spirit and a freeze of the Creed against legitimate development.",
                 "Orthodoxy distinguishes economic sending from eternal procession. The Son is not excluded from the Spirit’s work in history.",
                 [{"id": "basil", "name": "Basil"}, {"id": "gregory-nazianzen", "name": "Gregory Nazianzen"}, {"id": "gregory-nyssa", "name": "Gregory of Nyssa"}]),
            trad("lutheran", "Lutheran", "The creeds of the ancient Church.",
                 ["Augsburg Confession I receives the Nicene faith. Anti-trinitarian movements are rejected. The Filioque is retained with the Latin liturgical tradition.",
                  "Lutheran scholasticism restates the doctrine with less independent speculation than medieval Latin theology, but without departing from it."],
                 "The Reformation is a reform of the Church’s gospel, not a revision of the doctrine of God. To deny the Trinity is to leave the catholic faith.",
                 "Orthodoxy objects to the Filioque; some modern Protestants treat the doctrine as speculative surplus.",
                 "Lutherans bind themselves to the ecumenical creeds as a rule of faith subordinate to Scripture yet binding as its right interpretation.",
                 [{"id": "luther", "name": "Martin Luther"}, {"id": "melanchthon", "name": "Philip Melanchthon"}, {"id": None, "name": "Athanasian Creed"}]),
            trad("reformed", "Reformed / Calvinist", "One God in three persons; Institutes I.13.",
                 ["Calvin defends the Nicene faith against anti-trinitarians and warns against curiosity. The Filioque is generally retained. Later Reformed orthodoxy develops a careful doctrine of the decrees and the missions.",
                  "The Westminster Confession II restates classical Western trinitarianism."],
                 "Scripture names Father, Son, and Spirit as God, yet God is one. The Church’s technical vocabulary (person, essence) is a hedge around that confession.",
                 "Eastern objections to the Filioque apply. Unitarians claim the technical terms go beyond Scripture.",
                 "Reformed theology treats the terms as necessary to preserve biblical teaching, not as equal to it. Some recent Reformed writers are more open to Eastern concerns about the Filioque’s politics and wording.",
                 [{"id": "calvin", "name": "John Calvin"}, {"id": None, "name": "Westminster Confession"}, {"id": "athanasius", "name": "Athanasius"}]),
        ],
        agreements=["There is one God.", "Father, Son, and Spirit are each fully God.", "The persons are not mere masks.", "Arianism and modalism are heresy.", "Baptism is into the triune Name."],
        clashes=[
            clash("I. Filioque", ["From the Father and the Son.", "From the Father alone.", "Western creed retained.", "Western creed retained."]),
            clash("II. Monarchy of the Father", ["Affirmed with Filioque nuances.", "The structural principle of unity.", "Affirmed via the creeds.", "Affirmed via the creeds."]),
        ],
        timeline=[
            {"date": "325 / 381", "title": "Nicaea and Constantinople", "figureId": "athanasius", "significance": "Homoousios and the full divinity of the Spirit.", "extra": "The Creed of 381 is the shared dogmatic text."},
            {"date": "late 4th c.", "title": "Cappadocian settlement", "figureId": "basil", "significance": "Ousia and hypostasis distinguished.", "extra": "The Eastern grammar of the Trinity."},
            {"date": "c. 400–420", "title": "Augustine, De Trinitate", "figureId": "augustine", "significance": "Latin psychological and relational analysis.", "extra": "The seedbed of later Filioque theology."},
            {"date": "1054 and after", "title": "Filioque conflict", "figureId": None, "significance": "Creedal addition becomes a mark of schism.", "extra": "New Advent’s Filioque article maps the history."},
        ],
        sources=[
            src("Catholic Encyclopedia", "The Blessed Trinity", "https://www.newadvent.org/cathen/15047a.htm", "New Advent"),
            src("Augustine", "On the Trinity", "https://www.newadvent.org/fathers/1301.htm", "New Advent"),
            src("Basil", "On the Holy Spirit", "https://www.newadvent.org/fathers/3203.htm", "New Advent"),
            src("Gregory Nazianzen", "Theological Orations", "https://www.newadvent.org/fathers/3102.htm", "New Advent"),
            src("Thomas Aquinas", "ST I QQ.27–43", "texts/summa.html?part=prima&q=27&a=1", "Treatise on the Trinity"),
            src("Augsburg Confession", "Article I", "https://bookofconcord.org/augsburg-confession/", "Book of Concord"),
            src("John Calvin", "Institutes I.13", "https://www.ccel.org/ccel/calvin/institutes", "CCEL"),
            src("Catholic Encyclopedia", "Filioque", "https://www.newadvent.org/cathen/06073a.htm", "New Advent"),
        ],
        thread=[{"id": "trinity", "name": "Trinity", "current": True}, {"id": "holy-spirit", "name": "Holy Spirit"},
                {"id": "incarnation", "name": "Incarnation"}],
        related=[{"id": "holy-spirit", "name": "Holy Spirit"}, {"id": "incarnation", "name": "Incarnation"},
                 {"id": "church", "name": "Church"}, {"id": "scripture-tradition", "name": "Scripture & Tradition"}],
    )

    EXHIBITS["atonement"] = exhibit(
        id="atonement", domain="Salvation", title="Atonement", latin="Redemptio",
        centralQuestion="How does Christ’s death and resurrection reconcile us to God?",
        definition="Atonement describes the saving work of Christ by which sin and death are overcome and humanity is reconciled to God. Scripture uses images of sacrifice, victory, ransom, healing, and representation.",
        lead="Irenaeus’ recapitulation, patristic Christus Victor, Anselm’s satisfaction, Reformation penal substitution, and moral-influence accounts coexist and compete. The clash is over which image governs the others.",
        questionQuote="Does the Cross chiefly satisfy justice, conquer death, heal nature—or all of these in a certain order?",
        questionNote="All four traditions confess that Christ died for us and rose. They clash over wrath, substitution, scope, and how the Eucharist applies the one Cross.",
        deeperQuestions=["Is the atonement primarily victory, satisfaction, or penalty-bearing?", "Is its scope universal or particular?", "How is the Cross applied to persons?", "What does ‘wrath’ mean when predicated of the Father?"],
        glance={"rows": glance_rows([
            ("Governing image", ["Satisfaction and sacrifice, with victory retained.", "Christus Victor and therapeutic theosis.", "Victory and substitution held together (Luther).", "Penal substitution in union with Christ."]),
            ("Scope", ["Sufficient for all; applied through faith and sacraments.", "For the life of the world; received in synergy.", "Universal promise; received by faith.", "Particular redemption of the elect (classical)."]),
            ("Application", ["Sacraments and living faith.", "Mysteries and theosis.", "Word and Sacrament.", "Effectual calling and faith."]),
        ])},
        traditions=[
            trad("catholic", "Catholic", "Satisfaction, sacrifice, and the application of the Cross.",
                 ["Catholic theology receives Anselm’s insight that sin requires satisfaction, while retaining victory over death. Aquinas integrates merit, satisfaction, and sacrifice. The Cross is once for all; the Mass applies its fruits.",
                  "Redemption is objective in Christ and must be subjectively received. Limited-atonement schemes are refused in favor of a universal sufficient cause applied particularly."],
                 "Sin is both guilt and wound. A merely exemplary death cannot satisfy justice or destroy death. The God-man can offer a satisfaction of infinite worth.",
                 "Orthodoxy fears over-juridicalizing. Protestants fear that Mass-as-sacrifice and merit obscure the finished work.",
                 "The Mass does not add a second Calvary. Satisfaction language names the moral order of the universe, not a pagan transaction inside the Trinity.",
                 [{"id": "aquinas", "name": "Thomas Aquinas"}, {"id": None, "name": "Anselm of Canterbury"}, {"id": "athanasius", "name": "Athanasius"}]),
            trad("orthodox", "Eastern Orthodox", "Death destroyed; nature healed.",
                 ["The Incarnation and Pascha restore the image and open theosis. Juridical categories are not denied but are not allowed to dominate. Recapitulation (Irenaeus) and the destruction of death (Athanasius) set the frame.",
                  "The whole Christ-event—incarnation, death, descent, resurrection, ascension—is the atonement."],
                 "If the problem is death and corruption, the medicine must be life. God became man that man might become god—not by nature, but by participation.",
                 "Western substitutionary accounts ask whether this takes guilt and wrath with full seriousness.",
                 "Orthodoxy reads wrath as the experience of divine love by those who reject it, and guilt as healed in the same Pascha that conquers death.",
                 [{"id": "irenaeus", "name": "Irenaeus"}, {"id": "athanasius", "name": "Athanasius"}, {"id": "maximus", "name": "Maximus the Confessor"}]),
            trad("lutheran", "Lutheran", "Christ the sin-bearer and the victory of God.",
                 ["Luther’s atonement theology is both Christus Victor and a stark exchange: Christ bears sin, curse, and wrath; we receive righteousness. The Cross is preached as promise.",
                  "Universal atonement is typically affirmed: Christ died for all; unbelief rejects a gift truly given."],
                 "The law’s accusation is real. Only a substitute who is God and man can silence it. Victory over the devil is the public face of that same exchange.",
                 "Reformed particularists argue this makes the Cross ineffectual for many. Catholics argue Luther’s ‘wrath on the Son’ language is too mythological.",
                 "Lutherans preach a Cross that is for you. Particular efficacy is located in faith created by the Word, not in a narrowed intention at Calvary.",
                 [{"id": "luther", "name": "Martin Luther"}, {"id": "melanchthon", "name": "Philip Melanchthon"}, {"id": None, "name": "Augsburg Confession"}]),
            trad("reformed", "Reformed / Calvinist", "Penal substitution and particular redemption.",
                 ["Classical Reformed theology teaches that Christ bears the penalty due to the elect, satisfying justice. Union with Christ makes the exchange ours. Dort defined limited atonement against a merely potential universalism.",
                  "Christus Victor and priestly intercession remain. The disagreement with Lutherans is especially over the design of the atonement."],
                 "If Christ paid for all in the same way, all would be saved, or the payment was not a true payment. Particular redemption protects both justice and grace.",
                 "Lutherans, Catholics, Orthodox, and Arminians hear a restriction of John 3:16 and of the Church’s mission.",
                 "Reformed preachers distinguish sufficient value from efficient design, and insist the free offer of the Gospel is sincere.",
                 [{"id": "calvin", "name": "John Calvin"}, {"id": None, "name": "Synod of Dort"}, {"id": None, "name": "Westminster Confession"}]),
        ],
        agreements=["Christ died for sins and rose.", "No other name saves.", "The Cross is once for all in history.", "The atonement must be received.", "Sin and death are both in view."],
        clashes=[
            clash("I. Governing metaphor", ["Satisfaction/sacrifice.", "Victory and healing.", "Exchange and victory.", "Penal substitution."]),
            clash("II. Scope", ["Sufficient for all, applied particularly.", "For the life of the world.", "Universal intention.", "Particular redemption of the elect."]),
        ],
        timeline=[
            {"date": "2nd c.", "title": "Irenaeus — recapitulation", "figureId": "irenaeus", "significance": "Christ sums up Adam and restores the image.", "extra": "Against Heresies V."},
            {"date": "c. 318", "title": "Athanasius — On the Incarnation", "figureId": "athanasius", "significance": "Death destroyed by the Word’s own death.", "extra": "Foundational for East and West."},
            {"date": "1098", "title": "Anselm — Cur Deus Homo", "figureId": None, "significance": "Satisfaction theory shapes the Latin Middle Ages.", "extra": "CCEL PD translations."},
            {"date": "16th c.", "title": "Reformation substitution debates", "figureId": "luther", "significance": "Penal and victory motifs intensify; scope later splits Lutherans and Reformed.", "extra": "Calvin Institutes II.16–17; Dort on atonement."},
        ],
        sources=[
            src("Catholic Encyclopedia", "Atonement", "https://www.newadvent.org/cathen/02055a.htm", "New Advent"),
            src("Irenaeus", "Against Heresies", "https://www.newadvent.org/fathers/0103.htm", "New Advent"),
            src("Athanasius", "On the Incarnation", "https://www.newadvent.org/fathers/2802.htm", "New Advent"),
            src("Anselm", "Cur Deus Homo", "https://www.ccel.org/ccel/anselm/basic_works", "CCEL"),
            src("Thomas Aquinas", "ST III QQ.46–49", "texts/summa.html?part=tertia&q=48&a=1", "Passion of Christ"),
            src("John Calvin", "Institutes II.16–17", "https://www.ccel.org/ccel/calvin/institutes", "CCEL"),
            src("Augsburg Confession", "Articles III–IV", "https://bookofconcord.org/augsburg-confession/", "Book of Concord"),
        ],
        thread=[{"id": "incarnation", "name": "Incarnation"}, {"id": "atonement", "name": "Atonement", "current": True},
                {"id": "justification", "name": "Justification"}, {"id": "eucharist", "name": "Eucharist"}],
        related=[{"id": "incarnation", "name": "Incarnation"}, {"id": "grace", "name": "Grace"},
                 {"id": "justification", "name": "Justification"}, {"id": "original-sin", "name": "Original Sin"}],
    )

    EXHIBITS["church"] = exhibit(
        id="church", domain="Ecclesiology", title="Church", latin="Ecclesia",
        centralQuestion="Where is the one Church, and by what marks is she known?",
        definition="The Church is the community called together in Christ, formed by apostolic witness, nourished by word and sacrament, and sent as a sign of the Kingdom.",
        lead="The four marks—one, holy, catholic, apostolic—are confessed by all, then filled with rival content: Roman primacy, eucharistic conciliarity, or Word-and-sacrament without a single historic see.",
        questionQuote="Is the Church a visible hierarchy, a eucharistic communion of local churches, or the congregation where the Gospel is purely preached?",
        questionNote="No classical tradition treats the Church as a mere voluntary club. They clash over primacy, succession, and the boundary of the true Church.",
        deeperQuestions=["What kind of primacy belongs to Rome?", "Is apostolic succession episcopal or doctrinal?", "Can there be salvation outside the visible Church?", "Who may define dogma?"],
        glance={"rows": glance_rows([
            ("What the Church is", ["Visible hierarchical society; Body of Christ.", "Eucharistic communion of local churches.", "Congregation of believers around Word and Sacrament.", "The elect, gathered in visible congregations."]),
            ("Primacy", ["Universal jurisdiction of the Roman See.", "Primus inter pares; conciliarity.", "No necessary historic see.", "Christ alone as head; no papal jurisdiction."]),
            ("Succession", ["Unbroken episcopal ordination in communion with Rome.", "Apostolic episcopate and patristic faith.", "Succession in apostolic doctrine; episcopacy optional.", "Succession in doctrine; presbyterian order common."]),
        ])},
        traditions=[
            trad("catholic", "Catholic", "One, holy, catholic, apostolic—with Petrine primacy.",
                 ["Catholic ecclesiology confesses a visible society with apostolic succession, seven sacraments, and the teaching office of the bishops in communion with the Pope. Unity is visible communion, not only charity.",
                  "Extra ecclesiam nulla salus is interpreted with care for invincible ignorance, yet the Church remains the ordinary means of salvation."],
                 "Matthew 16, John 21, and the early Roman witness (Clement, Irenaeus, Leo) ground a real primacy. A purely invisible church cannot be the pillar and ground of the truth.",
                 "Orthodoxy rejects universal jurisdiction. Protestants reject both the papacy and the claim that unity requires one historic see.",
                 "Catholic theology distinguishes abusive exercise from the office itself and reads the Petrine ministry as service to unity, not as a rival to Christ the Head.",
                 [{"id": "cyprian", "name": "Cyprian"}, {"id": None, "name": "Leo the Great"}, {"id": "ignatius", "name": "Ignatius"}]),
            trad("orthodox", "Eastern Orthodox", "Conciliar, eucharistic, episcopal.",
                 ["The fullness of the Church is in the local eucharistic assembly with its bishop. Ecumenical Councils and the consensus of the Fathers define the faith. Roman universal ordinary jurisdiction is rejected.",
                  "Primacy, where recognized, is of honor and service within conciliarity. Continuity with the apostolic and patristic Church is the measure of catholicity."],
                 "Ignatius already binds Church, bishop, and Eucharist. The first millennium’s conciliar practice, not later papal definitions, is the rule.",
                 "Catholics argue that conciliarity without a living primate cannot settle disputes. Protestants argue that both East and West over-identify the Church with hierarchy.",
                 "Orthodoxy points to the survival of the faith through councils, liturgy, and the Fathers without a universal monarch.",
                 [{"id": "ignatius", "name": "Ignatius of Antioch"}, {"id": None, "name": "Photius"}, {"id": None, "name": "Ecumenical Councils"}]),
            trad("lutheran", "Lutheran", "Where the Word is preached and the sacraments given.",
                 ["Augsburg VII: the Church is the congregation of saints in which the Gospel is taught purely and the sacraments administered rightly. Episcopal polity may be retained as human right; it is not of the essence.",
                  "There is a visible church with hypocrites mixed in (AC VIII). Rome is not the necessary center."],
                 "The Church is created by the Word, not the Word by the Church. The marks must be audible and sacramental, or the Church becomes a legal corporation.",
                 "Catholics and Orthodox hear a reduction of apostolicity to a doctrine-checklist. Reformed critics sometimes want stricter discipline and a more explicit doctrine of the invisible elect.",
                 "Lutherans distinguish the Church’s essence from her beneficial order. Bishops may serve unity; they do not constitute it apart from the Gospel.",
                 [{"id": "luther", "name": "Martin Luther"}, {"id": "melanchthon", "name": "Philip Melanchthon"}, {"id": None, "name": "Augsburg Confession"}]),
            trad("reformed", "Reformed / Calvinist", "Word, sacrament, and discipline.",
                 ["Calvin’s Institutes IV treats the Church as mother of believers and as a visible society with officers. The marks typically include Word, sacraments, and often discipline. Christ alone is Head.",
                  "Presbyterian order is common; congregational variants exist. Apostolic succession is doctrinal and ministerial, not a pipeline of episcopal character."],
                 "A church without discipline is a body without joints. Yet no bishop of Rome can bind the conscience beside Scripture.",
                 "Lutherans fear discipline becoming a third mark that eclipses the Gospel. Catholics and Orthodox deny that a 16th-century reconstitution can be the apostolic Church.",
                 "Reformed theology claims catholicity by continuity of doctrine and by the promises of Christ, not by an unbroken canonical paper trail.",
                 [{"id": "calvin", "name": "John Calvin"}, {"id": None, "name": "Westminster Confession"}, {"id": None, "name": "Scots Confession"}]),
        ],
        agreements=["The Church is Christ’s Body.", "She is one, holy, catholic, and apostolic in the Creed.", "Word and sacrament belong to her life.", "Schism is a wound.", "Christ, not a merely human founder, is Lord of the Church."],
        clashes=[
            clash("I. Primacy of Rome", ["Universal jurisdiction.", "Honor, not jurisdiction.", "Not necessary.", "Rejected."]),
            clash("II. Apostolic succession", ["Episcopal, in communion with Peter’s successor.", "Episcopal and patristic.", "Doctrinal; polity secondary.", "Doctrinal and presbyterial."]),
        ],
        timeline=[
            {"date": "c. 110", "title": "Ignatius", "figureId": "ignatius", "significance": "Bishop, Eucharist, and catholic Church.", "extra": "Letters to the Smyrnaeans, Magnesians, Romans."},
            {"date": "251", "title": "Cyprian — Unity of the Church", "figureId": "cyprian", "significance": "One episcopate; later read differently by Rome and others.", "extra": "On the Unity of the Church."},
            {"date": "1054 / 1204", "title": "East–West rupture", "figureId": None, "significance": "Schism hardens over primacy, Filioque, and later the sack of Constantinople.", "extra": "New Advent, Eastern Schism."},
            {"date": "1530", "title": "Augsburg VII–VIII", "figureId": "luther", "significance": "Reformation definition by marks rather than see.", "extra": "Book of Concord."},
        ],
        sources=[
            src("Catholic Encyclopedia", "The Church", "https://www.newadvent.org/cathen/03744a.htm", "New Advent"),
            src("Cyprian", "On the Unity of the Church", "https://www.newadvent.org/fathers/050701.htm", "New Advent"),
            src("Ignatius", "Letters", "https://www.newadvent.org/fathers/0104.htm", "New Advent"),
            src("Augsburg Confession", "Articles VII–VIII", "https://bookofconcord.org/augsburg-confession/", "Book of Concord"),
            src("John Calvin", "Institutes IV", "https://www.ccel.org/ccel/calvin/institutes", "CCEL"),
            src("Catholic Encyclopedia", "Eastern Schism", "https://www.newadvent.org/cathen/13535a.htm", "New Advent"),
        ],
        thread=[{"id": "church", "name": "Church", "current": True}, {"id": "sacraments", "name": "Sacraments"},
                {"id": "scripture-tradition", "name": "Scripture & Tradition"}],
        related=[{"id": "sacraments", "name": "Sacraments"}, {"id": "eucharist", "name": "Eucharist"},
                 {"id": "scripture-tradition", "name": "Scripture & Tradition"}, {"id": "baptism", "name": "Baptism"}],
    )
    return EXHIBITS
