# Remaining exhibits; imported by build_exhibits.py via exec.
from copy import deepcopy

# This file is exec'd with COLS, trad, clash, src, glance_rows, exhibit in namespace.

def add_all(EXHIBITS):
    EXHIBITS["justification"] = exhibit(
        id="justification", domain="Salvation", title="Justification", latin="Iustificatio",
        centralQuestion="How is the sinner made—or declared—righteous before God?",
        definition="Justification names God’s gracious act of setting the sinner right with Himself through Christ. Traditions differ over how declaration, forgiveness, inward renewal, faith, and works belong together.",
        lead="Paul’s language of dikaiosynē is received by all four traditions, yet they divide over whether justifying righteousness is infused or imputed, whether faith alone is the instrument, and whether justification and sanctification are one process or two gifts.",
        questionQuote="When God justifies a sinner, does He change the person, or declare a verdict—or both?",
        questionNote="All four traditions reject Pelagian self-justification. The clash is over the mechanism and the ground of acceptance.",
        deeperQuestions=[
            "Is justifying righteousness inherent or alien (Christ’s, imputed)?",
            "Is faith alone the instrument, or faith formed by charity?",
            "Do works increase justification or only evidence it?",
            "Are justification and sanctification distinct?",
            "Can justification be lost?",
        ],
        glance={"rows": glance_rows([
            ("What justification is", [
                "Forgiveness and infusion of sanctifying grace.",
                "Being made righteous as participation in divine life.",
                "Forensic declaration: Christ’s righteousness received by faith.",
                "Forensic declaration grounded in union with Christ.",
            ]),
            ("Instrument", [
                "Faith formed by charity; beginning, foundation, and root.",
                "Faith lived in synergy, prayer, and the mysteries.",
                "Faith alone (sola fide), created by the Word.",
                "Faith alone, the empty hand receiving Christ.",
            ]),
            ("Works", [
                "Works in grace truly merit increase of grace and glory.",
                "Works are the path of theosis, not a rival currency.",
                "Necessary fruits; not the cause of justification.",
                "Necessary fruits of union; never the ground of acceptance.",
            ]),
            ("Can it be lost?", [
                "Mortal sin destroys sanctifying grace; restoration by penance.",
                "The path can be abandoned; repentance restores communion.",
                "Faith can be lost; apostasy is real.",
                "The elect persevere; temporary faith may fail.",
            ]),
        ])},
        traditions=[
            trad("catholic", "Catholic", "Forgiveness and the renewal of the inner man.",
                 ["Trent teaches that justification is not only the remission of sins but also sanctification and renewal. Faith is the beginning, yet faith without hope and charity does not perfectly unite the believer to Christ. The righteousness is real in the believer.",
                  "Works done in grace are not the price of the first justification. They are fruits of Christ living in the believer and, as such, meritorious. Penance restores justification lost by mortal sin."],
                 "Scripture speaks of a new creation, of charity poured into hearts, of becoming partakers of the divine nature. A merely external covering would leave Paul’s language of inner renewal unexplained.",
                 "Reformers argue that mixing renewal into justification makes assurance impossible and turns faith into a work. James, they say, speaks of evidential works, not of the cause of acceptance.",
                 "Catholic theology replies that the first justification is entirely unearned. Subsequent works are gifts of God in us. Assurance is found in hope, the sacraments, and perseverance—not in a bare extra nos verdict isolated from charity.",
                 [{"id": "augustine", "name": "Augustine"}, {"id": "aquinas", "name": "Thomas Aquinas"}, {"id": None, "name": "Council of Trent"}]),
            trad("orthodox", "Eastern Orthodox", "Righteousness as communion and healing.",
                 ["Eastern writers are less driven by the forensic–transformative polarity of the Latin West. Righteousness is life in communion with God. Juridical metaphors are retained, but healing, illumination, and deification dominate.",
                  "Faith and works are coordinated within synergy. Baptism, Eucharist, and ascesis are the ordinary path. ‘Justification’ is not isolated as a courtroom moment that then needs a second doctrine of sanctification."],
                 "If the goal is theosis, being made righteous cannot be a mere verdict. Irenaeus, Athanasius, and the liturgical tradition read salvation as recapitulation and participation.",
                 "Western Protestants fear that synergy blurs grace; Catholics sometimes want a more precise account of infused habits. Some Orthodox worry that Western forensic language reduces salvation to legal fiction.",
                 "Orthodoxy asks to be judged by its liturgy and Fathers. Juridical language is real but not exhaustive. The clash is often a clash of grammars as much as of conclusions.",
                 [{"id": "athanasius", "name": "Athanasius"}, {"id": "chrysostom", "name": "John Chrysostom"}, {"id": "maximus", "name": "Maximus the Confessor"}]),
            trad("lutheran", "Lutheran", "Faith counted as righteousness for Christ’s sake.",
                 ["The Augsburg Confession teaches that we are justified by faith apart from works of the law. Christ’s righteousness is imputed; sins are forgiven; the conscience is set free. Good works necessarily follow living faith.",
                  "The Formula of Concord guards both sola fide and the reality of new obedience. Simul justus et peccator names the believer’s condition: righteous in Christ, sinner in himself, until the resurrection."],
                 "The terrified conscience cannot rest on a process of interior transformation as the ground of peace with God. Romans 3–5 and Galatians demand a verdict based on Christ, received by faith.",
                 "Catholics and Orthodox argue that this severs Paul from James and risks antinomianism. Reformed critics press for a tighter doctrine of perseverance and limited atonement.",
                 "Lutherans insist that forensic justification grounds rather than excludes new life. James is about a dead faith that never was living. The Gospel offer is universal; faith can be lost.",
                 [{"id": "luther", "name": "Martin Luther"}, {"id": "melanchthon", "name": "Philip Melanchthon"}, {"id": None, "name": "Augsburg Confession"}]),
            trad("reformed", "Reformed / Calvinist", "Imputed righteousness in union with Christ.",
                 ["Calvin distinguishes justification from sanctification while insisting both are given in union with Christ. Justification is the imputation of Christ’s righteousness and the forgiveness of sins. It is once for all for those who are in Christ.",
                  "The ordo salutis typically places effectual calling and regeneration before faith, then justification, adoption, sanctification, and perseverance. Works evidence justification; they never constitute it."],
                 "If the righteousness by which we stand is our own inherent justice, we are still under law. Union with Christ allows both a forensic verdict and a real new life without mixing their grounds.",
                 "Lutherans worry that limited atonement and perseverance schemes restrict the Gospel offer. Catholics reject alien righteousness as a legal fiction. Arminians reject unconditional election as the backdrop.",
                 "Reformed theology replies that imputation is no fiction if Christ is truly ours by union. The Gospel is freely preached; it is effectual in the elect. Perseverance is God’s keeping, not human self-security.",
                 [{"id": "calvin", "name": "John Calvin"}, {"id": None, "name": "Westminster Assembly"}, {"id": None, "name": "Synod of Dort"}]),
        ],
        agreements=[
            "No one is justified by unaided works of the law.",
            "Christ is the sole meritorious cause of justification.",
            "Faith is indispensable.",
            "A merely verbal faith without love is dead.",
            "Good works belong to the Christian life.",
        ],
        clashes=[
            clash("I. Infused or imputed righteousness?", [
                "Inherent righteousness by sanctifying grace, together with forgiveness.",
                "Righteousness as participation; less invested in the polarity.",
                "Alien righteousness of Christ, imputed; simul justus et peccator.",
                "Alien righteousness imputed in union with Christ.",
            ]),
            clash("II. Faith alone?", [
                "Faith formed by charity; ‘faith alone’ rejected as Trent understood it.",
                "Faith lived; the slogan is not native.",
                "Sola fide as the article by which the Church stands.",
                "Sola fide, with works as evidence.",
            ]),
            clash("III. Can justification be lost?", [
                "Yes, by mortal sin; restored by penance.",
                "Communion can be broken and restored.",
                "Yes; apostasy is possible.",
                "The elect do not finally fall; others may have temporary faith.",
            ]),
        ],
        timeline=[
            {"date": "c. 396–430", "title": "Augustine on grace and righteousness", "figureId": "augustine",
             "significance": "Set the Western terms for grace, faith, and the law.",
             "extra": "On the Spirit and the Letter remains a shared text claimed by later rivals."},
            {"date": "13th c.", "title": "Aquinas on justification", "figureId": "aquinas",
             "significance": "ST I-II Q.113 analyzes justification as a movement of the soul by grace.",
             "extra": "Infusion, remission, and the motion of free will are coordinated."},
            {"date": "1517–1530", "title": "Luther and Augsburg IV", "figureId": "luther",
             "significance": "Sola fide and imputed righteousness become Reformation hallmarks.",
             "extra": "Augsburg Confession IV is the Lutheran definition."},
            {"date": "1547", "title": "Trent, Session VI", "figureId": None,
             "significance": "Catholic definition against both Pelagius and a purely extrinsic account.",
             "extra": "The canons remain the Catholic boundary."},
            {"date": "1619 / 1646", "title": "Dort and Westminster", "figureId": "calvin",
             "significance": "Reformed ordo salutis and perseverance clarified.",
             "extra": "Justification is located within election and union with Christ."},
        ],
        sources=[
            src("Catholic Encyclopedia", "Justification", "https://www.newadvent.org/cathen/08573a.htm", "New Advent"),
            src("Augustine", "On the Spirit and the Letter", "https://www.newadvent.org/fathers/1502.htm", "New Advent"),
            src("Thomas Aquinas", "ST I-II Q.113", "texts/summa.html?part=prima-sec&q=113&a=1", "On Justification"),
            src("Council of Trent", "Session VI", "https://www.newadvent.org/cathen/15030c.htm", "New Advent"),
            src("Augsburg Confession", "Article IV", "https://bookofconcord.org/augsburg-confession/", "Book of Concord"),
            src("John Calvin", "Institutes III.11–18", "https://www.ccel.org/ccel/calvin/institutes", "CCEL"),
            src("Athanasius", "On the Incarnation", "https://www.newadvent.org/fathers/2802.htm", "New Advent"),
        ],
        thread=[{"id": "grace", "name": "Grace"}, {"id": "justification", "name": "Justification", "current": True},
                {"id": "faith-works", "name": "Faith & Works"}, {"id": "atonement", "name": "Atonement"}],
        related=[{"id": "grace", "name": "Grace"}, {"id": "faith-works", "name": "Faith & Works"},
                 {"id": "original-sin", "name": "Original Sin"}, {"id": "atonement", "name": "Atonement"},
                 {"id": "predestination", "name": "Predestination"}, {"id": "baptism", "name": "Baptism"}],
    )

    EXHIBITS["eucharist"] = exhibit(
        id="eucharist", domain="Sacraments", title="Eucharist", latin="Eucharistia",
        centralQuestion="How is Christ present in the Lord’s Supper, and is it a sacrifice?",
        definition="The Eucharist is the sacramental memorial of Christ’s death and resurrection in which the Church gives thanks, receives communion, and proclaims Christ’s presence among His people.",
        lead="Ignatius, the mystagogical catecheses, medieval real-presence debates, and Reformation controversies over sacrifice and presence make the Eucharist both a mark of division and a sign of hoped-for unity.",
        questionQuote="Is the bread Christ’s Body, a sign of His Body, or both—and what does that mean for sacrifice?",
        questionNote="All four traditions treat the Supper as instituted by Christ. They clash over conversion of the elements, sacrifice, reservation, and who may preside.",
        deeperQuestions=[
            "Is the presence substantial, sacramental, spiritual, or memorial?",
            "Is the Eucharist a propitiatory sacrifice?",
            "May the reserved sacrament be adored?",
            "Who may validly preside?",
            "What is required of communicants?",
        ],
        glance={"rows": glance_rows([
            ("Presence", [
                "Transubstantiation: substance converted, appearances remain.",
                "Real change confessed; not bound to Aristotelian substance.",
                "Sacramental union: Body and Blood in, with, and under bread and wine.",
                "True spiritual presence by the Spirit; elements remain bread and wine.",
            ]),
            ("Sacrifice", [
                "The Mass is a true propitiatory sacrifice applying the Cross.",
                "The Divine Liturgy is a true bloodless sacrifice.",
                "The Supper is a testament and distribution of the Cross, not a new propitiation.",
                "A spiritual sacrifice of praise; not propitiatory.",
            ]),
            ("Reservation / adoration", [
                "Adoration of the reserved sacrament follows from real presence.",
                "Reserved Gifts for communion of the sick; liturgical reverence.",
                "Generally no extra-liturgical adoration; presence tied to use.",
                "No reservation for adoration; signs and seals of the covenant.",
            ]),
            ("Who presides", [
                "A validly ordained priest.",
                "A priest in apostolic succession under the bishop.",
                "A called and ordained minister.",
                "A lawfully called minister of the Word.",
            ]),
        ])},
        traditions=[
            trad("catholic", "Catholic", "True, real, and substantial presence; the Mass is a sacrifice.",
                 ["Catholic doctrine teaches transubstantiation. The Eucharist is both communion and propitiatory sacrifice, applying the one sacrifice of the Cross. Adoration of the reserved sacrament follows from the real presence.",
                  "Trent anathematizes purely symbolic and purely spiritual accounts that deny substantial presence. Aquinas’s treatise remains the classic Latin synthesis of sign, presence, and sacrifice."],
                 "The words of institution, John 6, 1 Corinthians 10–11, and the unanimous patristic realism (Ignatius, Cyril, John of Damascus) demand more than a figure of speech. If Christ is truly present, the Church’s offering is His.",
                 "Protestants argue that transubstantiation rests on a disputed philosophy and that a repeated propitiatory sacrifice undermines the once-for-all Cross (Hebrews).",
                 "Catholics reply that the Mass does not repeat or add to Calvary; it makes the one sacrifice present. Substance language protects, rather than replaces, the mystery.",
                 [{"id": "aquinas", "name": "Thomas Aquinas"}, {"id": "ignatius", "name": "Ignatius of Antioch"}, {"id": None, "name": "Council of Trent"}]),
            trad("orthodox", "Eastern Orthodox", "The mysteries of the Body and Blood in the Liturgy.",
                 ["Orthodoxy affirms the real presence and the sacrificial character of the Liturgy without binding the faithful to the Latin term transubstantiation. The change is confessed in the epiclesis and the Fathers.",
                  "Communion is the climax of the Church’s common life and is inseparable from the bishop and the one altar. Reservation is for the sick, not for Latin-style extra-liturgical cultus as a separate system."],
                 "The anaphora and the mystagogical tradition leave no room for a mere memorial. The Church offers and receives what Christ is.",
                 "Latin scholastics pressed for more definition; Reformers charged both East and West with sacrificing the Cross again. Some Orthodox reject Latin adoration practices as a distortion.",
                 "Orthodoxy prefers liturgical confession to metaphysical system. The mystery is known in communion, not in a theory of accidents.",
                 [{"id": None, "name": "Cyril of Jerusalem"}, {"id": None, "name": "John of Damascus"}, {"id": "chrysostom", "name": "John Chrysostom"}]),
            trad("lutheran", "Lutheran", "Sacramental union: ‘in, with, and under.’",
                 ["Luther rejected transubstantiation as an unnecessary theory but insisted against Zwingli that Christ’s Body and Blood are truly present. The Formula of Concord teaches sacramental union.",
                  "The Mass as a human work of propitiation is rejected. The Supper is Christ’s testament, distributing the fruits of the Cross. Private masses and extra-liturgical adoration are refused; liturgical reverence remains."],
                 "‘This is my body’ must be allowed to stand. A mere spiritual or memorial presence cannot sustain the warning of 1 Corinthians 11 against unworthy eating of the Body.",
                 "Reformed theology accuses Lutherans of ubiquity and capernaitic eating. Catholics say sacramental union stops short of the conversion the Fathers imply.",
                 "Lutherans distinguish a local enclosing of Christ in bread from a sacramental presence by Christ’s promise. Christ is at the right hand and at the altar because His humanity is not confined.",
                 [{"id": "luther", "name": "Martin Luther"}, {"id": None, "name": "Formula of Concord"}, {"id": "melanchthon", "name": "Philip Melanchthon"}]),
            trad("reformed", "Reformed / Calvinist", "Spiritual feeding by faith; signs and seals.",
                 ["Calvin taught a true participation in Christ by the Spirit, not a bare memorial and not a local presence of the Body in the elements. The bread remains bread; it is a sign and seal of the covenant.",
                  "The Mass as propitiatory sacrifice is rejected. Frequent communion is encouraged; worthy receiving requires faith. Zwinglian memorialism is a further, more radical Reformed-adjacent option, not identical with Calvin."],
                 "Christ’s risen body is in heaven. The Spirit lifts the faithful to feed on Him there. This protects both real communion and the integrity of Christ’s humanity.",
                 "Lutherans hear a Nestorian split between sign and reality. Catholics hear a denial of the Incarnation’s logic of real presence in earthly signs.",
                 "Calvin insists the communion is real, not imaginary. The disagreement is about the mode of presence, not about whether Christ is given to faith.",
                 [{"id": "calvin", "name": "John Calvin"}, {"id": None, "name": "Westminster Confession"}, {"id": None, "name": "Zwingli (memorial)"}]),
        ],
        agreements=[
            "Christ instituted the Supper.",
            "It is to be received in the Church with thanksgiving.",
            "It proclaims the Lord’s death until He comes.",
            "Unworthy receiving is a real danger.",
            "The one Cross is not repeated as a new bloody sacrifice in history.",
        ],
        clashes=[
            clash("I. Mode of presence", [
                "Transubstantiation.",
                "Real change, liturgically confessed.",
                "Sacramental union.",
                "Spiritual presence by the Spirit.",
            ]),
            clash("II. Sacrifice", [
                "Propitiatory application of the Cross.",
                "Bloodless sacrifice of the Liturgy.",
                "Testament, not a new propitiation.",
                "Sacrifice of praise, not propitiation.",
            ]),
            clash("III. Adoration of the elements", [
                "Yes, because Christ is substantially present.",
                "Liturgical reverence; different extra-liturgical practice.",
                "Presence for use, not for extra-liturgical cultus.",
                "No; that would adore bread.",
            ]),
        ],
        timeline=[
            {"date": "c. 110", "title": "Ignatius of Antioch", "figureId": "ignatius",
             "significance": "Called the Eucharist the flesh of Christ; linked it to the bishop.",
             "extra": "Early realism against docetism."},
            {"date": "4th–8th c.", "title": "Cyril of Jerusalem and John of Damascus", "figureId": None,
             "significance": "Catechesis and dogmatic exposition of the change of the elements.",
             "extra": "Eastern liturgical theology of the mysteries."},
            {"date": "13th c.", "title": "Aquinas and transubstantiation", "figureId": "aquinas",
             "significance": "Latin metaphysical definition of the conversion.",
             "extra": "Later defined at Lateran IV and Trent."},
            {"date": "1520s–1577", "title": "Reformation controversies", "figureId": "luther",
             "significance": "Luther, Zwingli, Calvin, and Trent fix the modern map of disagreement.",
             "extra": "Marburg 1529 showed the Lutheran–Reformed split over ‘is’."},
        ],
        sources=[
            src("Catholic Encyclopedia", "Eucharist", "https://www.newadvent.org/cathen/05572c.htm", "New Advent"),
            src("Ignatius", "Letter to the Smyrnaeans", "https://www.newadvent.org/fathers/0109.htm", "New Advent"),
            src("Cyril of Jerusalem", "Mystagogical Catecheses", "https://www.newadvent.org/fathers/3101.htm", "New Advent"),
            src("Thomas Aquinas", "ST III QQ.73–83", "texts/summa.html?part=tertia&q=75&a=1", "Real presence"),
            src("Augsburg Confession", "Article X", "https://bookofconcord.org/augsburg-confession/", "Book of Concord"),
            src("John Calvin", "Institutes IV.17", "https://www.ccel.org/ccel/calvin/institutes", "CCEL"),
            src("John of Damascus", "Exact Exposition IV", "https://www.newadvent.org/fathers/3304.htm", "New Advent"),
        ],
        thread=[{"id": "incarnation", "name": "Incarnation"}, {"id": "atonement", "name": "Atonement"},
                {"id": "eucharist", "name": "Eucharist", "current": True}, {"id": "sacraments", "name": "Sacraments"}],
        related=[{"id": "sacraments", "name": "Sacraments"}, {"id": "baptism", "name": "Baptism"},
                 {"id": "church", "name": "Church"}, {"id": "atonement", "name": "Atonement"},
                 {"id": "incarnation", "name": "Incarnation"}],
    )
    return EXHIBITS
