#!/usr/bin/env python3
import json
from pathlib import Path

ROOT = Path("/workspace/artifacts/lumen_fidei")
TOOLS = ROOT / "tools"

ns = {}
exec((TOOLS / "build_exhibits.py").read_text(), ns)
exec((TOOLS / "build_exhibits_more.py").read_text(), ns)
ns["add_all"](ns["EXHIBITS"])
exec((TOOLS / "build_exhibits_rest.py").read_text(), ns)
ns["add_rest"](ns["EXHIBITS"])
exec((TOOLS / "build_exhibits_remaining.py").read_text(), ns)
ns["add_remaining"](ns["EXHIBITS"], ns["exhibit"], ns["trad"], ns["clash"], ns["src"], ns["glance_rows"])

exhibits = ns["EXHIBITS"]
out = ROOT / "js" / "concept-exhibits-data.js"
payload = json.dumps(exhibits, ensure_ascii=False, indent=2)
header = (
    "/* Auto-generated by tools/emit_exhibits.py — four-tradition encyclopedia exhibits. */\n"
    "window.CONCEPT_EXHIBITS = "
)
out.write_text(header + payload + ";\n", encoding="utf-8")
print("wrote", out, "bytes", out.stat().st_size)
print("ids:", ", ".join(sorted(exhibits)))
print("count:", len(exhibits))
for k, v in sorted(exhibits.items()):
    ntrad = len(v.get("traditions") or [])
    nsrc = len(v.get("sources") or [])
    nclash = len(v.get("clashes") or [])
    print(f"  {k:22} traditions={ntrad} clashes={nclash} sources={nsrc} title={v.get('title')}")
